.global music_danny_start
.global music_danny_end
.global music_door_start
.global music_door_end
.global music_haggstrom_start
.global music_haggstrom_end
.global music_key_start
.global music_key_end
.global music_living_mice_start
.global music_living_mice_end
.global music_mice_on_venus_start
.global music_mice_on_venus_end
.global music_minecraft_start
.global music_minecraft_end
.global music_moog_city_2_start
.global music_moog_city_2_end
.global music_oxygene_start
.global music_oxygene_end
.global music_subwoofer_lullaby_start
.global music_subwoofer_lullaby_end
.global music_equinoxe_start
.global music_equinoxe_end

.section .rodata

music_danny_start:
.incbin "assets/music/danny.aac"
music_danny_end:

music_door_start:
.incbin "assets/music/door.aac"
music_door_end:

music_haggstrom_start:
.incbin "assets/music/haggstrom.aac"
music_haggstrom_end:

music_key_start:
.incbin "assets/music/key.aac"
music_key_end:

music_living_mice_start:
.incbin "assets/music/living_mice.aac"
music_living_mice_end:

music_mice_on_venus_start:
.incbin "assets/music/mice_on_venus.aac"
music_mice_on_venus_end:

music_minecraft_start:
.incbin "assets/music/minecraft.aac"
music_minecraft_end:

music_moog_city_2_start:
.incbin "assets/music/moog_city_2.aac"
music_moog_city_2_end:

music_oxygene_start:
.incbin "assets/music/oxygene.aac"
music_oxygene_end:

music_subwoofer_lullaby_start:
.incbin "assets/music/subwoofer_lullaby.aac"
music_subwoofer_lullaby_end:

music_equinoxe_start:
.incbin "assets/music/equinoxe.aac"
music_equinoxe_end:
