#if defined(MCPE_IOS) || defined(__APPLE__)
.section __TEXT,__const
#else
.section .rodata
#endif

.globl PCM_NEW_weather_rain1
.globl _PCM_NEW_weather_rain1
PCM_NEW_weather_rain1:
_PCM_NEW_weather_rain1:
.incbin "assets/sound/pcm/weather_rain1.pcm"

.globl PCM_NEW_weather_rain2
.globl _PCM_NEW_weather_rain2
PCM_NEW_weather_rain2:
_PCM_NEW_weather_rain2:
.incbin "assets/sound/pcm/weather_rain2.pcm"

.globl PCM_NEW_weather_rain3
.globl _PCM_NEW_weather_rain3
PCM_NEW_weather_rain3:
_PCM_NEW_weather_rain3:
.incbin "assets/sound/pcm/weather_rain3.pcm"

.globl PCM_NEW_weather_rain4
.globl _PCM_NEW_weather_rain4
PCM_NEW_weather_rain4:
_PCM_NEW_weather_rain4:
.incbin "assets/sound/pcm/weather_rain4.pcm"

.globl PCM_NEW_weather_rain5
.globl _PCM_NEW_weather_rain5
PCM_NEW_weather_rain5:
_PCM_NEW_weather_rain5:
.incbin "assets/sound/pcm/weather_rain5.pcm"

.globl PCM_NEW_weather_rain6
.globl _PCM_NEW_weather_rain6
PCM_NEW_weather_rain6:
_PCM_NEW_weather_rain6:
.incbin "assets/sound/pcm/weather_rain6.pcm"

.globl PCM_NEW_weather_rain7
.globl _PCM_NEW_weather_rain7
PCM_NEW_weather_rain7:
_PCM_NEW_weather_rain7:
.incbin "assets/sound/pcm/weather_rain7.pcm"

.globl PCM_NEW_weather_rain8
.globl _PCM_NEW_weather_rain8
PCM_NEW_weather_rain8:
_PCM_NEW_weather_rain8:
.incbin "assets/sound/pcm/weather_rain8.pcm"

.globl PCM_NEW_weather_thunder1
.globl _PCM_NEW_weather_thunder1
PCM_NEW_weather_thunder1:
_PCM_NEW_weather_thunder1:
.incbin "assets/sound/pcm/weather_thunder1.pcm"

.globl PCM_NEW_weather_thunder2
.globl _PCM_NEW_weather_thunder2
PCM_NEW_weather_thunder2:
_PCM_NEW_weather_thunder2:
.incbin "assets/sound/pcm/weather_thunder2.pcm"

.globl PCM_NEW_weather_thunder3
.globl _PCM_NEW_weather_thunder3
PCM_NEW_weather_thunder3:
_PCM_NEW_weather_thunder3:
.incbin "assets/sound/pcm/weather_thunder3.pcm"

.globl PCM_NEW_fish_flop1
.globl _PCM_NEW_fish_flop1
PCM_NEW_fish_flop1:
_PCM_NEW_fish_flop1:
.incbin "assets/sound/pcm/fish_flop1.pcm"

.globl PCM_NEW_fish_flop2
.globl _PCM_NEW_fish_flop2
PCM_NEW_fish_flop2:
_PCM_NEW_fish_flop2:
.incbin "assets/sound/pcm/fish_flop2.pcm"

.globl PCM_NEW_fish_flop3
.globl _PCM_NEW_fish_flop3
PCM_NEW_fish_flop3:
_PCM_NEW_fish_flop3:
.incbin "assets/sound/pcm/fish_flop3.pcm"

.globl PCM_NEW_fish_flop4
.globl _PCM_NEW_fish_flop4
PCM_NEW_fish_flop4:
_PCM_NEW_fish_flop4:
.incbin "assets/sound/pcm/fish_flop4.pcm"

.globl PCM_NEW_fish_hurt1
.globl _PCM_NEW_fish_hurt1
PCM_NEW_fish_hurt1:
_PCM_NEW_fish_hurt1:
.incbin "assets/sound/pcm/fish_hurt1.pcm"

.globl PCM_NEW_fish_hurt2
.globl _PCM_NEW_fish_hurt2
PCM_NEW_fish_hurt2:
_PCM_NEW_fish_hurt2:
.incbin "assets/sound/pcm/fish_hurt2.pcm"

.globl PCM_NEW_fish_hurt3
.globl _PCM_NEW_fish_hurt3
PCM_NEW_fish_hurt3:
_PCM_NEW_fish_hurt3:
.incbin "assets/sound/pcm/fish_hurt3.pcm"

.globl PCM_NEW_fish_hurt4
.globl _PCM_NEW_fish_hurt4
PCM_NEW_fish_hurt4:
_PCM_NEW_fish_hurt4:
.incbin "assets/sound/pcm/fish_hurt4.pcm"

.globl PCM_NEW_fish_swim1
.globl _PCM_NEW_fish_swim1
PCM_NEW_fish_swim1:
_PCM_NEW_fish_swim1:
.incbin "assets/sound/pcm/fish_swim1.pcm"

.globl PCM_NEW_fish_swim2
.globl _PCM_NEW_fish_swim2
PCM_NEW_fish_swim2:
_PCM_NEW_fish_swim2:
.incbin "assets/sound/pcm/fish_swim2.pcm"

.globl PCM_NEW_fish_swim3
.globl _PCM_NEW_fish_swim3
PCM_NEW_fish_swim3:
_PCM_NEW_fish_swim3:
.incbin "assets/sound/pcm/fish_swim3.pcm"

.globl PCM_NEW_fish_swim4
.globl _PCM_NEW_fish_swim4
PCM_NEW_fish_swim4:
_PCM_NEW_fish_swim4:
.incbin "assets/sound/pcm/fish_swim4.pcm"

.globl PCM_NEW_fish_swim5
.globl _PCM_NEW_fish_swim5
PCM_NEW_fish_swim5:
_PCM_NEW_fish_swim5:
.incbin "assets/sound/pcm/fish_swim5.pcm"

.globl PCM_NEW_fish_swim6
.globl _PCM_NEW_fish_swim6
PCM_NEW_fish_swim6:
_PCM_NEW_fish_swim6:
.incbin "assets/sound/pcm/fish_swim6.pcm"

.globl PCM_NEW_fish_swim7
.globl _PCM_NEW_fish_swim7
PCM_NEW_fish_swim7:
_PCM_NEW_fish_swim7:
.incbin "assets/sound/pcm/fish_swim7.pcm"

.globl PCM_NEW_turtle_armor
.globl _PCM_NEW_turtle_armor
PCM_NEW_turtle_armor:
_PCM_NEW_turtle_armor:
.incbin "assets/sound/pcm/turtle_armor.pcm"

.globl PCM_NEW_turtle_death1
.globl _PCM_NEW_turtle_death1
PCM_NEW_turtle_death1:
_PCM_NEW_turtle_death1:
.incbin "assets/sound/pcm/turtle_death1.pcm"

.globl PCM_NEW_turtle_death2
.globl _PCM_NEW_turtle_death2
PCM_NEW_turtle_death2:
_PCM_NEW_turtle_death2:
.incbin "assets/sound/pcm/turtle_death2.pcm"

.globl PCM_NEW_turtle_death3
.globl _PCM_NEW_turtle_death3
PCM_NEW_turtle_death3:
_PCM_NEW_turtle_death3:
.incbin "assets/sound/pcm/turtle_death3.pcm"

.globl PCM_NEW_turtle_hurt1
.globl _PCM_NEW_turtle_hurt1
PCM_NEW_turtle_hurt1:
_PCM_NEW_turtle_hurt1:
.incbin "assets/sound/pcm/turtle_hurt1.pcm"

.globl PCM_NEW_turtle_hurt2
.globl _PCM_NEW_turtle_hurt2
PCM_NEW_turtle_hurt2:
_PCM_NEW_turtle_hurt2:
.incbin "assets/sound/pcm/turtle_hurt2.pcm"

.globl PCM_NEW_turtle_hurt3
.globl _PCM_NEW_turtle_hurt3
PCM_NEW_turtle_hurt3:
_PCM_NEW_turtle_hurt3:
.incbin "assets/sound/pcm/turtle_hurt3.pcm"

.globl PCM_NEW_turtle_hurt4
.globl _PCM_NEW_turtle_hurt4
PCM_NEW_turtle_hurt4:
_PCM_NEW_turtle_hurt4:
.incbin "assets/sound/pcm/turtle_hurt4.pcm"

.globl PCM_NEW_turtle_hurt5
.globl _PCM_NEW_turtle_hurt5
PCM_NEW_turtle_hurt5:
_PCM_NEW_turtle_hurt5:
.incbin "assets/sound/pcm/turtle_hurt5.pcm"

.globl PCM_NEW_turtle_idle1
.globl _PCM_NEW_turtle_idle1
PCM_NEW_turtle_idle1:
_PCM_NEW_turtle_idle1:
.incbin "assets/sound/pcm/turtle_idle1.pcm"

.globl PCM_NEW_turtle_idle2
.globl _PCM_NEW_turtle_idle2
PCM_NEW_turtle_idle2:
_PCM_NEW_turtle_idle2:
.incbin "assets/sound/pcm/turtle_idle2.pcm"

.globl PCM_NEW_turtle_idle3
.globl _PCM_NEW_turtle_idle3
PCM_NEW_turtle_idle3:
_PCM_NEW_turtle_idle3:
.incbin "assets/sound/pcm/turtle_idle3.pcm"

.globl PCM_NEW_turtle_walk1
.globl _PCM_NEW_turtle_walk1
PCM_NEW_turtle_walk1:
_PCM_NEW_turtle_walk1:
.incbin "assets/sound/pcm/turtle_walk1.pcm"

.globl PCM_NEW_turtle_walk2
.globl _PCM_NEW_turtle_walk2
PCM_NEW_turtle_walk2:
_PCM_NEW_turtle_walk2:
.incbin "assets/sound/pcm/turtle_walk2.pcm"

.globl PCM_NEW_turtle_walk3
.globl _PCM_NEW_turtle_walk3
PCM_NEW_turtle_walk3:
_PCM_NEW_turtle_walk3:
.incbin "assets/sound/pcm/turtle_walk3.pcm"

.globl PCM_NEW_turtle_walk4
.globl _PCM_NEW_turtle_walk4
PCM_NEW_turtle_walk4:
_PCM_NEW_turtle_walk4:
.incbin "assets/sound/pcm/turtle_walk4.pcm"

.globl PCM_NEW_turtle_walk5
.globl _PCM_NEW_turtle_walk5
PCM_NEW_turtle_walk5:
_PCM_NEW_turtle_walk5:
.incbin "assets/sound/pcm/turtle_walk5.pcm"

.globl PCM_NEW_turtle_egg_drop_egg1
.globl _PCM_NEW_turtle_egg_drop_egg1
PCM_NEW_turtle_egg_drop_egg1:
_PCM_NEW_turtle_egg_drop_egg1:
.incbin "assets/sound/pcm/turtle_egg_drop_egg1.pcm"

.globl PCM_NEW_turtle_egg_drop_egg2
.globl _PCM_NEW_turtle_egg_drop_egg2
PCM_NEW_turtle_egg_drop_egg2:
_PCM_NEW_turtle_egg_drop_egg2:
.incbin "assets/sound/pcm/turtle_egg_drop_egg2.pcm"

.globl PCM_NEW_turtle_egg_egg_break1
.globl _PCM_NEW_turtle_egg_egg_break1
PCM_NEW_turtle_egg_egg_break1:
_PCM_NEW_turtle_egg_egg_break1:
.incbin "assets/sound/pcm/turtle_egg_egg_break1.pcm"

.globl PCM_NEW_turtle_egg_egg_break2
.globl _PCM_NEW_turtle_egg_egg_break2
PCM_NEW_turtle_egg_egg_break2:
_PCM_NEW_turtle_egg_egg_break2:
.incbin "assets/sound/pcm/turtle_egg_egg_break2.pcm"

.globl PCM_NEW_turtle_egg_egg_crack1
.globl _PCM_NEW_turtle_egg_egg_crack1
PCM_NEW_turtle_egg_egg_crack1:
_PCM_NEW_turtle_egg_egg_crack1:
.incbin "assets/sound/pcm/turtle_egg_egg_crack1.pcm"

.globl PCM_NEW_turtle_egg_egg_crack2
.globl _PCM_NEW_turtle_egg_egg_crack2
PCM_NEW_turtle_egg_egg_crack2:
_PCM_NEW_turtle_egg_egg_crack2:
.incbin "assets/sound/pcm/turtle_egg_egg_crack2.pcm"

.globl PCM_NEW_turtle_egg_egg_crack3
.globl _PCM_NEW_turtle_egg_egg_crack3
PCM_NEW_turtle_egg_egg_crack3:
_PCM_NEW_turtle_egg_egg_crack3:
.incbin "assets/sound/pcm/turtle_egg_egg_crack3.pcm"

.globl PCM_NEW_turtle_egg_egg_crack4
.globl _PCM_NEW_turtle_egg_egg_crack4
PCM_NEW_turtle_egg_egg_crack4:
_PCM_NEW_turtle_egg_egg_crack4:
.incbin "assets/sound/pcm/turtle_egg_egg_crack4.pcm"

.globl PCM_NEW_turtle_egg_egg_crack5
.globl _PCM_NEW_turtle_egg_egg_crack5
PCM_NEW_turtle_egg_egg_crack5:
_PCM_NEW_turtle_egg_egg_crack5:
.incbin "assets/sound/pcm/turtle_egg_egg_crack5.pcm"

.globl PCM_NEW_turtle_egg_jump_egg1
.globl _PCM_NEW_turtle_egg_jump_egg1
PCM_NEW_turtle_egg_jump_egg1:
_PCM_NEW_turtle_egg_jump_egg1:
.incbin "assets/sound/pcm/turtle_egg_jump_egg1.pcm"

.globl PCM_NEW_turtle_egg_jump_egg2
.globl _PCM_NEW_turtle_egg_jump_egg2
PCM_NEW_turtle_egg_jump_egg2:
_PCM_NEW_turtle_egg_jump_egg2:
.incbin "assets/sound/pcm/turtle_egg_jump_egg2.pcm"

.globl PCM_NEW_turtle_egg_jump_egg3
.globl _PCM_NEW_turtle_egg_jump_egg3
PCM_NEW_turtle_egg_jump_egg3:
_PCM_NEW_turtle_egg_jump_egg3:
.incbin "assets/sound/pcm/turtle_egg_jump_egg3.pcm"

.globl PCM_NEW_turtle_egg_jump_egg4
.globl _PCM_NEW_turtle_egg_jump_egg4
PCM_NEW_turtle_egg_jump_egg4:
_PCM_NEW_turtle_egg_jump_egg4:
.incbin "assets/sound/pcm/turtle_egg_jump_egg4.pcm"

.globl PCM_NEW_turtle_swim_swim1
.globl _PCM_NEW_turtle_swim_swim1
PCM_NEW_turtle_swim_swim1:
_PCM_NEW_turtle_swim_swim1:
.incbin "assets/sound/pcm/turtle_swim_swim1.pcm"

.globl PCM_NEW_turtle_swim_swim2
.globl _PCM_NEW_turtle_swim_swim2
PCM_NEW_turtle_swim_swim2:
_PCM_NEW_turtle_swim_swim2:
.incbin "assets/sound/pcm/turtle_swim_swim2.pcm"

.globl PCM_NEW_turtle_swim_swim3
.globl _PCM_NEW_turtle_swim_swim3
PCM_NEW_turtle_swim_swim3:
_PCM_NEW_turtle_swim_swim3:
.incbin "assets/sound/pcm/turtle_swim_swim3.pcm"

.globl PCM_NEW_turtle_swim_swim4
.globl _PCM_NEW_turtle_swim_swim4
PCM_NEW_turtle_swim_swim4:
_PCM_NEW_turtle_swim_swim4:
.incbin "assets/sound/pcm/turtle_swim_swim4.pcm"

.globl PCM_NEW_turtle_swim_swim5
.globl _PCM_NEW_turtle_swim_swim5
PCM_NEW_turtle_swim_swim5:
_PCM_NEW_turtle_swim_swim5:
.incbin "assets/sound/pcm/turtle_swim_swim5.pcm"

.globl PCM_NEW_turtle_baby_death1
.globl _PCM_NEW_turtle_baby_death1
PCM_NEW_turtle_baby_death1:
_PCM_NEW_turtle_baby_death1:
.incbin "assets/sound/pcm/turtle_baby_death1.pcm"

.globl PCM_NEW_turtle_baby_death2
.globl _PCM_NEW_turtle_baby_death2
PCM_NEW_turtle_baby_death2:
_PCM_NEW_turtle_baby_death2:
.incbin "assets/sound/pcm/turtle_baby_death2.pcm"

.globl PCM_NEW_turtle_baby_egg_hatched1
.globl _PCM_NEW_turtle_baby_egg_hatched1
PCM_NEW_turtle_baby_egg_hatched1:
_PCM_NEW_turtle_baby_egg_hatched1:
.incbin "assets/sound/pcm/turtle_baby_egg_hatched1.pcm"

.globl PCM_NEW_turtle_baby_egg_hatched2
.globl _PCM_NEW_turtle_baby_egg_hatched2
PCM_NEW_turtle_baby_egg_hatched2:
_PCM_NEW_turtle_baby_egg_hatched2:
.incbin "assets/sound/pcm/turtle_baby_egg_hatched2.pcm"

.globl PCM_NEW_turtle_baby_egg_hatched3
.globl _PCM_NEW_turtle_baby_egg_hatched3
PCM_NEW_turtle_baby_egg_hatched3:
_PCM_NEW_turtle_baby_egg_hatched3:
.incbin "assets/sound/pcm/turtle_baby_egg_hatched3.pcm"

.globl PCM_NEW_turtle_baby_hurt1
.globl _PCM_NEW_turtle_baby_hurt1
PCM_NEW_turtle_baby_hurt1:
_PCM_NEW_turtle_baby_hurt1:
.incbin "assets/sound/pcm/turtle_baby_hurt1.pcm"

.globl PCM_NEW_turtle_baby_hurt2
.globl _PCM_NEW_turtle_baby_hurt2
PCM_NEW_turtle_baby_hurt2:
_PCM_NEW_turtle_baby_hurt2:
.incbin "assets/sound/pcm/turtle_baby_hurt2.pcm"

.globl PCM_NEW_turtle_baby_shamble1
.globl _PCM_NEW_turtle_baby_shamble1
PCM_NEW_turtle_baby_shamble1:
_PCM_NEW_turtle_baby_shamble1:
.incbin "assets/sound/pcm/turtle_baby_shamble1.pcm"

.globl PCM_NEW_turtle_baby_shamble2
.globl _PCM_NEW_turtle_baby_shamble2
PCM_NEW_turtle_baby_shamble2:
_PCM_NEW_turtle_baby_shamble2:
.incbin "assets/sound/pcm/turtle_baby_shamble2.pcm"

.globl PCM_NEW_turtle_baby_shamble3
.globl _PCM_NEW_turtle_baby_shamble3
PCM_NEW_turtle_baby_shamble3:
_PCM_NEW_turtle_baby_shamble3:
.incbin "assets/sound/pcm/turtle_baby_shamble3.pcm"

.globl PCM_NEW_turtle_baby_shamble4
.globl _PCM_NEW_turtle_baby_shamble4
PCM_NEW_turtle_baby_shamble4:
_PCM_NEW_turtle_baby_shamble4:
.incbin "assets/sound/pcm/turtle_baby_shamble4.pcm"

.globl PCM_NEW_wolf_bark1
.globl _PCM_NEW_wolf_bark1
PCM_NEW_wolf_bark1:
_PCM_NEW_wolf_bark1:
.incbin "assets/sound/pcm/wolf_bark1.pcm"

.globl PCM_NEW_wolf_bark2
.globl _PCM_NEW_wolf_bark2
PCM_NEW_wolf_bark2:
_PCM_NEW_wolf_bark2:
.incbin "assets/sound/pcm/wolf_bark2.pcm"

.globl PCM_NEW_wolf_bark3
.globl _PCM_NEW_wolf_bark3
PCM_NEW_wolf_bark3:
_PCM_NEW_wolf_bark3:
.incbin "assets/sound/pcm/wolf_bark3.pcm"

.globl PCM_NEW_wolf_death
.globl _PCM_NEW_wolf_death
PCM_NEW_wolf_death:
_PCM_NEW_wolf_death:
.incbin "assets/sound/pcm/wolf_death.pcm"

.globl PCM_NEW_wolf_growl1
.globl _PCM_NEW_wolf_growl1
PCM_NEW_wolf_growl1:
_PCM_NEW_wolf_growl1:
.incbin "assets/sound/pcm/wolf_growl1.pcm"

.globl PCM_NEW_wolf_growl2
.globl _PCM_NEW_wolf_growl2
PCM_NEW_wolf_growl2:
_PCM_NEW_wolf_growl2:
.incbin "assets/sound/pcm/wolf_growl2.pcm"

.globl PCM_NEW_wolf_growl3
.globl _PCM_NEW_wolf_growl3
PCM_NEW_wolf_growl3:
_PCM_NEW_wolf_growl3:
.incbin "assets/sound/pcm/wolf_growl3.pcm"

.globl PCM_NEW_wolf_howl1
.globl _PCM_NEW_wolf_howl1
PCM_NEW_wolf_howl1:
_PCM_NEW_wolf_howl1:
.incbin "assets/sound/pcm/wolf_howl1.pcm"

.globl PCM_NEW_wolf_howl2
.globl _PCM_NEW_wolf_howl2
PCM_NEW_wolf_howl2:
_PCM_NEW_wolf_howl2:
.incbin "assets/sound/pcm/wolf_howl2.pcm"

.globl PCM_NEW_wolf_hurt1
.globl _PCM_NEW_wolf_hurt1
PCM_NEW_wolf_hurt1:
_PCM_NEW_wolf_hurt1:
.incbin "assets/sound/pcm/wolf_hurt1.pcm"

.globl PCM_NEW_wolf_hurt2
.globl _PCM_NEW_wolf_hurt2
PCM_NEW_wolf_hurt2:
_PCM_NEW_wolf_hurt2:
.incbin "assets/sound/pcm/wolf_hurt2.pcm"

.globl PCM_NEW_wolf_hurt3
.globl _PCM_NEW_wolf_hurt3
PCM_NEW_wolf_hurt3:
_PCM_NEW_wolf_hurt3:
.incbin "assets/sound/pcm/wolf_hurt3.pcm"

.globl PCM_NEW_wolf_panting
.globl _PCM_NEW_wolf_panting
PCM_NEW_wolf_panting:
_PCM_NEW_wolf_panting:
.incbin "assets/sound/pcm/wolf_panting.pcm"

.globl PCM_NEW_wolf_shake
.globl _PCM_NEW_wolf_shake
PCM_NEW_wolf_shake:
_PCM_NEW_wolf_shake:
.incbin "assets/sound/pcm/wolf_shake.pcm"

.globl PCM_NEW_wolf_step1
.globl _PCM_NEW_wolf_step1
PCM_NEW_wolf_step1:
_PCM_NEW_wolf_step1:
.incbin "assets/sound/pcm/wolf_step1.pcm"

.globl PCM_NEW_wolf_step2
.globl _PCM_NEW_wolf_step2
PCM_NEW_wolf_step2:
_PCM_NEW_wolf_step2:
.incbin "assets/sound/pcm/wolf_step2.pcm"

.globl PCM_NEW_wolf_step3
.globl _PCM_NEW_wolf_step3
PCM_NEW_wolf_step3:
_PCM_NEW_wolf_step3:
.incbin "assets/sound/pcm/wolf_step3.pcm"

.globl PCM_NEW_wolf_step4
.globl _PCM_NEW_wolf_step4
PCM_NEW_wolf_step4:
_PCM_NEW_wolf_step4:
.incbin "assets/sound/pcm/wolf_step4.pcm"

.globl PCM_NEW_wolf_step5
.globl _PCM_NEW_wolf_step5
PCM_NEW_wolf_step5:
_PCM_NEW_wolf_step5:
.incbin "assets/sound/pcm/wolf_step5.pcm"

.globl PCM_NEW_wolf_whine
.globl _PCM_NEW_wolf_whine
PCM_NEW_wolf_whine:
_PCM_NEW_wolf_whine:
.incbin "assets/sound/pcm/wolf_whine.pcm"

.globl PCM_NEW_slime_attack1
.globl _PCM_NEW_slime_attack1
PCM_NEW_slime_attack1:
_PCM_NEW_slime_attack1:
.incbin "assets/sound/pcm/slime_attack1.pcm"

.globl PCM_NEW_slime_attack2
.globl _PCM_NEW_slime_attack2
PCM_NEW_slime_attack2:
_PCM_NEW_slime_attack2:
.incbin "assets/sound/pcm/slime_attack2.pcm"

.globl PCM_NEW_slime_big1
.globl _PCM_NEW_slime_big1
PCM_NEW_slime_big1:
_PCM_NEW_slime_big1:
.incbin "assets/sound/pcm/slime_big1.pcm"

.globl PCM_NEW_slime_big2
.globl _PCM_NEW_slime_big2
PCM_NEW_slime_big2:
_PCM_NEW_slime_big2:
.incbin "assets/sound/pcm/slime_big2.pcm"

.globl PCM_NEW_slime_big3
.globl _PCM_NEW_slime_big3
PCM_NEW_slime_big3:
_PCM_NEW_slime_big3:
.incbin "assets/sound/pcm/slime_big3.pcm"

.globl PCM_NEW_slime_big4
.globl _PCM_NEW_slime_big4
PCM_NEW_slime_big4:
_PCM_NEW_slime_big4:
.incbin "assets/sound/pcm/slime_big4.pcm"

.globl PCM_NEW_slime_small1
.globl _PCM_NEW_slime_small1
PCM_NEW_slime_small1:
_PCM_NEW_slime_small1:
.incbin "assets/sound/pcm/slime_small1.pcm"

.globl PCM_NEW_slime_small2
.globl _PCM_NEW_slime_small2
PCM_NEW_slime_small2:
_PCM_NEW_slime_small2:
.incbin "assets/sound/pcm/slime_small2.pcm"

.globl PCM_NEW_slime_small3
.globl _PCM_NEW_slime_small3
PCM_NEW_slime_small3:
_PCM_NEW_slime_small3:
.incbin "assets/sound/pcm/slime_small3.pcm"

.globl PCM_NEW_slime_small4
.globl _PCM_NEW_slime_small4
PCM_NEW_slime_small4:
_PCM_NEW_slime_small4:
.incbin "assets/sound/pcm/slime_small4.pcm"

.globl PCM_NEW_slime_small5
.globl _PCM_NEW_slime_small5
PCM_NEW_slime_small5:
_PCM_NEW_slime_small5:
.incbin "assets/sound/pcm/slime_small5.pcm"

.globl PCM_NEW_water_heavy_splash
.globl _PCM_NEW_water_heavy_splash
PCM_NEW_water_heavy_splash:
_PCM_NEW_water_heavy_splash:
.incbin "assets/sound/pcm/water_heavy_splash.pcm"

.globl PCM_NEW_water_lava
.globl _PCM_NEW_water_lava
PCM_NEW_water_lava:
_PCM_NEW_water_lava:
.incbin "assets/sound/pcm/water_lava.pcm"

.globl PCM_NEW_water_lavapop
.globl _PCM_NEW_water_lavapop
PCM_NEW_water_lavapop:
_PCM_NEW_water_lavapop:
.incbin "assets/sound/pcm/water_lavapop.pcm"

.globl PCM_NEW_water_splash
.globl _PCM_NEW_water_splash
PCM_NEW_water_splash:
_PCM_NEW_water_splash:
.incbin "assets/sound/pcm/water_splash.pcm"

.globl PCM_NEW_water_splash2
.globl _PCM_NEW_water_splash2
PCM_NEW_water_splash2:
_PCM_NEW_water_splash2:
.incbin "assets/sound/pcm/water_splash2.pcm"

.globl PCM_NEW_water_swim1
.globl _PCM_NEW_water_swim1
PCM_NEW_water_swim1:
_PCM_NEW_water_swim1:
.incbin "assets/sound/pcm/water_swim1.pcm"

.globl PCM_NEW_water_swim10
.globl _PCM_NEW_water_swim10
PCM_NEW_water_swim10:
_PCM_NEW_water_swim10:
.incbin "assets/sound/pcm/water_swim10.pcm"

.globl PCM_NEW_water_swim11
.globl _PCM_NEW_water_swim11
PCM_NEW_water_swim11:
_PCM_NEW_water_swim11:
.incbin "assets/sound/pcm/water_swim11.pcm"

.globl PCM_NEW_water_swim12
.globl _PCM_NEW_water_swim12
PCM_NEW_water_swim12:
_PCM_NEW_water_swim12:
.incbin "assets/sound/pcm/water_swim12.pcm"

.globl PCM_NEW_water_swim13
.globl _PCM_NEW_water_swim13
PCM_NEW_water_swim13:
_PCM_NEW_water_swim13:
.incbin "assets/sound/pcm/water_swim13.pcm"

.globl PCM_NEW_water_swim14
.globl _PCM_NEW_water_swim14
PCM_NEW_water_swim14:
_PCM_NEW_water_swim14:
.incbin "assets/sound/pcm/water_swim14.pcm"

.globl PCM_NEW_water_swim15
.globl _PCM_NEW_water_swim15
PCM_NEW_water_swim15:
_PCM_NEW_water_swim15:
.incbin "assets/sound/pcm/water_swim15.pcm"

.globl PCM_NEW_water_swim16
.globl _PCM_NEW_water_swim16
PCM_NEW_water_swim16:
_PCM_NEW_water_swim16:
.incbin "assets/sound/pcm/water_swim16.pcm"

.globl PCM_NEW_water_swim17
.globl _PCM_NEW_water_swim17
PCM_NEW_water_swim17:
_PCM_NEW_water_swim17:
.incbin "assets/sound/pcm/water_swim17.pcm"

.globl PCM_NEW_water_swim18
.globl _PCM_NEW_water_swim18
PCM_NEW_water_swim18:
_PCM_NEW_water_swim18:
.incbin "assets/sound/pcm/water_swim18.pcm"

.globl PCM_NEW_water_swim2
.globl _PCM_NEW_water_swim2
PCM_NEW_water_swim2:
_PCM_NEW_water_swim2:
.incbin "assets/sound/pcm/water_swim2.pcm"

.globl PCM_NEW_water_swim3
.globl _PCM_NEW_water_swim3
PCM_NEW_water_swim3:
_PCM_NEW_water_swim3:
.incbin "assets/sound/pcm/water_swim3.pcm"

.globl PCM_NEW_water_swim4
.globl _PCM_NEW_water_swim4
PCM_NEW_water_swim4:
_PCM_NEW_water_swim4:
.incbin "assets/sound/pcm/water_swim4.pcm"

.globl PCM_NEW_water_swim5
.globl _PCM_NEW_water_swim5
PCM_NEW_water_swim5:
_PCM_NEW_water_swim5:
.incbin "assets/sound/pcm/water_swim5.pcm"

.globl PCM_NEW_water_swim6
.globl _PCM_NEW_water_swim6
PCM_NEW_water_swim6:
_PCM_NEW_water_swim6:
.incbin "assets/sound/pcm/water_swim6.pcm"

.globl PCM_NEW_water_swim7
.globl _PCM_NEW_water_swim7
PCM_NEW_water_swim7:
_PCM_NEW_water_swim7:
.incbin "assets/sound/pcm/water_swim7.pcm"

.globl PCM_NEW_water_swim8
.globl _PCM_NEW_water_swim8
PCM_NEW_water_swim8:
_PCM_NEW_water_swim8:
.incbin "assets/sound/pcm/water_swim8.pcm"

.globl PCM_NEW_water_swim9
.globl _PCM_NEW_water_swim9
PCM_NEW_water_swim9:
_PCM_NEW_water_swim9:
.incbin "assets/sound/pcm/water_swim9.pcm"

.globl PCM_NEW_water_water
.globl _PCM_NEW_water_water
PCM_NEW_water_water:
_PCM_NEW_water_water:
.incbin "assets/sound/pcm/water_water.pcm"

.globl PCM_NEW_pufferfish_blow_out1
.globl _PCM_NEW_pufferfish_blow_out1
PCM_NEW_pufferfish_blow_out1:
_PCM_NEW_pufferfish_blow_out1:
.incbin "assets/sound/pcm/pufferfish_blow_out1.pcm"

.globl PCM_NEW_pufferfish_blow_out2
.globl _PCM_NEW_pufferfish_blow_out2
PCM_NEW_pufferfish_blow_out2:
_PCM_NEW_pufferfish_blow_out2:
.incbin "assets/sound/pcm/pufferfish_blow_out2.pcm"

.globl PCM_NEW_pufferfish_blow_up1
.globl _PCM_NEW_pufferfish_blow_up1
PCM_NEW_pufferfish_blow_up1:
_PCM_NEW_pufferfish_blow_up1:
.incbin "assets/sound/pcm/pufferfish_blow_up1.pcm"

.globl PCM_NEW_pufferfish_blow_up2
.globl _PCM_NEW_pufferfish_blow_up2
PCM_NEW_pufferfish_blow_up2:
_PCM_NEW_pufferfish_blow_up2:
.incbin "assets/sound/pcm/pufferfish_blow_up2.pcm"

.globl PCM_NEW_pufferfish_death1
.globl _PCM_NEW_pufferfish_death1
PCM_NEW_pufferfish_death1:
_PCM_NEW_pufferfish_death1:
.incbin "assets/sound/pcm/pufferfish_death1.pcm"

.globl PCM_NEW_pufferfish_death2
.globl _PCM_NEW_pufferfish_death2
PCM_NEW_pufferfish_death2:
_PCM_NEW_pufferfish_death2:
.incbin "assets/sound/pcm/pufferfish_death2.pcm"

.globl PCM_NEW_pufferfish_flop1
.globl _PCM_NEW_pufferfish_flop1
PCM_NEW_pufferfish_flop1:
_PCM_NEW_pufferfish_flop1:
.incbin "assets/sound/pcm/pufferfish_flop1.pcm"

.globl PCM_NEW_pufferfish_flop2
.globl _PCM_NEW_pufferfish_flop2
PCM_NEW_pufferfish_flop2:
_PCM_NEW_pufferfish_flop2:
.incbin "assets/sound/pcm/pufferfish_flop2.pcm"

.globl PCM_NEW_pufferfish_flop3
.globl _PCM_NEW_pufferfish_flop3
PCM_NEW_pufferfish_flop3:
_PCM_NEW_pufferfish_flop3:
.incbin "assets/sound/pcm/pufferfish_flop3.pcm"

.globl PCM_NEW_pufferfish_flop4
.globl _PCM_NEW_pufferfish_flop4
PCM_NEW_pufferfish_flop4:
_PCM_NEW_pufferfish_flop4:
.incbin "assets/sound/pcm/pufferfish_flop4.pcm"

.globl PCM_NEW_pufferfish_hurt1
.globl _PCM_NEW_pufferfish_hurt1
PCM_NEW_pufferfish_hurt1:
_PCM_NEW_pufferfish_hurt1:
.incbin "assets/sound/pcm/pufferfish_hurt1.pcm"

.globl PCM_NEW_pufferfish_hurt2
.globl _PCM_NEW_pufferfish_hurt2
PCM_NEW_pufferfish_hurt2:
_PCM_NEW_pufferfish_hurt2:
.incbin "assets/sound/pcm/pufferfish_hurt2.pcm"

.globl PCM_NEW_pufferfish_sting1
.globl _PCM_NEW_pufferfish_sting1
PCM_NEW_pufferfish_sting1:
_PCM_NEW_pufferfish_sting1:
.incbin "assets/sound/pcm/pufferfish_sting1.pcm"

.globl PCM_NEW_pufferfish_sting2
.globl _PCM_NEW_pufferfish_sting2
PCM_NEW_pufferfish_sting2:
_PCM_NEW_pufferfish_sting2:
.incbin "assets/sound/pcm/pufferfish_sting2.pcm"

.globl PCM_NEW_squid_ambient1
.globl _PCM_NEW_squid_ambient1
PCM_NEW_squid_ambient1:
_PCM_NEW_squid_ambient1:
.incbin "assets/sound/pcm/squid_ambient1.pcm"

.globl PCM_NEW_squid_ambient2
.globl _PCM_NEW_squid_ambient2
PCM_NEW_squid_ambient2:
_PCM_NEW_squid_ambient2:
.incbin "assets/sound/pcm/squid_ambient2.pcm"

.globl PCM_NEW_squid_ambient3
.globl _PCM_NEW_squid_ambient3
PCM_NEW_squid_ambient3:
_PCM_NEW_squid_ambient3:
.incbin "assets/sound/pcm/squid_ambient3.pcm"

.globl PCM_NEW_squid_ambient4
.globl _PCM_NEW_squid_ambient4
PCM_NEW_squid_ambient4:
_PCM_NEW_squid_ambient4:
.incbin "assets/sound/pcm/squid_ambient4.pcm"

.globl PCM_NEW_squid_ambient5
.globl _PCM_NEW_squid_ambient5
PCM_NEW_squid_ambient5:
_PCM_NEW_squid_ambient5:
.incbin "assets/sound/pcm/squid_ambient5.pcm"

.globl PCM_NEW_squid_death1
.globl _PCM_NEW_squid_death1
PCM_NEW_squid_death1:
_PCM_NEW_squid_death1:
.incbin "assets/sound/pcm/squid_death1.pcm"

.globl PCM_NEW_squid_death2
.globl _PCM_NEW_squid_death2
PCM_NEW_squid_death2:
_PCM_NEW_squid_death2:
.incbin "assets/sound/pcm/squid_death2.pcm"

.globl PCM_NEW_squid_death3
.globl _PCM_NEW_squid_death3
PCM_NEW_squid_death3:
_PCM_NEW_squid_death3:
.incbin "assets/sound/pcm/squid_death3.pcm"

.globl PCM_NEW_squid_hurt1
.globl _PCM_NEW_squid_hurt1
PCM_NEW_squid_hurt1:
_PCM_NEW_squid_hurt1:
.incbin "assets/sound/pcm/squid_hurt1.pcm"

.globl PCM_NEW_squid_hurt2
.globl _PCM_NEW_squid_hurt2
PCM_NEW_squid_hurt2:
_PCM_NEW_squid_hurt2:
.incbin "assets/sound/pcm/squid_hurt2.pcm"

.globl PCM_NEW_squid_hurt3
.globl _PCM_NEW_squid_hurt3
PCM_NEW_squid_hurt3:
_PCM_NEW_squid_hurt3:
.incbin "assets/sound/pcm/squid_hurt3.pcm"

.globl PCM_NEW_squid_hurt4
.globl _PCM_NEW_squid_hurt4
PCM_NEW_squid_hurt4:
_PCM_NEW_squid_hurt4:
.incbin "assets/sound/pcm/squid_hurt4.pcm"

.globl PCM_NEW_squid_squirt1
.globl _PCM_NEW_squid_squirt1
PCM_NEW_squid_squirt1:
_PCM_NEW_squid_squirt1:
.incbin "assets/sound/pcm/squid_squirt1.pcm"

.globl PCM_NEW_squid_squirt2
.globl _PCM_NEW_squid_squirt2
PCM_NEW_squid_squirt2:
_PCM_NEW_squid_squirt2:
.incbin "assets/sound/pcm/squid_squirt2.pcm"

.globl PCM_NEW_squid_squirt3
.globl _PCM_NEW_squid_squirt3
PCM_NEW_squid_squirt3:
_PCM_NEW_squid_squirt3:
.incbin "assets/sound/pcm/squid_squirt3.pcm"

.globl PCM_NEW_polarbear_death1
.globl _PCM_NEW_polarbear_death1
PCM_NEW_polarbear_death1:
_PCM_NEW_polarbear_death1:
.incbin "assets/sound/pcm/polarbear_death1.pcm"

.globl PCM_NEW_polarbear_death2
.globl _PCM_NEW_polarbear_death2
PCM_NEW_polarbear_death2:
_PCM_NEW_polarbear_death2:
.incbin "assets/sound/pcm/polarbear_death2.pcm"

.globl PCM_NEW_polarbear_death3
.globl _PCM_NEW_polarbear_death3
PCM_NEW_polarbear_death3:
_PCM_NEW_polarbear_death3:
.incbin "assets/sound/pcm/polarbear_death3.pcm"

.globl PCM_NEW_polarbear_hurt1
.globl _PCM_NEW_polarbear_hurt1
PCM_NEW_polarbear_hurt1:
_PCM_NEW_polarbear_hurt1:
.incbin "assets/sound/pcm/polarbear_hurt1.pcm"

.globl PCM_NEW_polarbear_hurt2
.globl _PCM_NEW_polarbear_hurt2
PCM_NEW_polarbear_hurt2:
_PCM_NEW_polarbear_hurt2:
.incbin "assets/sound/pcm/polarbear_hurt2.pcm"

.globl PCM_NEW_polarbear_hurt3
.globl _PCM_NEW_polarbear_hurt3
PCM_NEW_polarbear_hurt3:
_PCM_NEW_polarbear_hurt3:
.incbin "assets/sound/pcm/polarbear_hurt3.pcm"

.globl PCM_NEW_polarbear_hurt4
.globl _PCM_NEW_polarbear_hurt4
PCM_NEW_polarbear_hurt4:
_PCM_NEW_polarbear_hurt4:
.incbin "assets/sound/pcm/polarbear_hurt4.pcm"

.globl PCM_NEW_polarbear_idle1
.globl _PCM_NEW_polarbear_idle1
PCM_NEW_polarbear_idle1:
_PCM_NEW_polarbear_idle1:
.incbin "assets/sound/pcm/polarbear_idle1.pcm"

.globl PCM_NEW_polarbear_idle2
.globl _PCM_NEW_polarbear_idle2
PCM_NEW_polarbear_idle2:
_PCM_NEW_polarbear_idle2:
.incbin "assets/sound/pcm/polarbear_idle2.pcm"

.globl PCM_NEW_polarbear_idle3
.globl _PCM_NEW_polarbear_idle3
PCM_NEW_polarbear_idle3:
_PCM_NEW_polarbear_idle3:
.incbin "assets/sound/pcm/polarbear_idle3.pcm"

.globl PCM_NEW_polarbear_idle4
.globl _PCM_NEW_polarbear_idle4
PCM_NEW_polarbear_idle4:
_PCM_NEW_polarbear_idle4:
.incbin "assets/sound/pcm/polarbear_idle4.pcm"

.globl PCM_NEW_polarbear_step1
.globl _PCM_NEW_polarbear_step1
PCM_NEW_polarbear_step1:
_PCM_NEW_polarbear_step1:
.incbin "assets/sound/pcm/polarbear_step1.pcm"

.globl PCM_NEW_polarbear_step2
.globl _PCM_NEW_polarbear_step2
PCM_NEW_polarbear_step2:
_PCM_NEW_polarbear_step2:
.incbin "assets/sound/pcm/polarbear_step2.pcm"

.globl PCM_NEW_polarbear_step3
.globl _PCM_NEW_polarbear_step3
PCM_NEW_polarbear_step3:
_PCM_NEW_polarbear_step3:
.incbin "assets/sound/pcm/polarbear_step3.pcm"

.globl PCM_NEW_polarbear_step4
.globl _PCM_NEW_polarbear_step4
PCM_NEW_polarbear_step4:
_PCM_NEW_polarbear_step4:
.incbin "assets/sound/pcm/polarbear_step4.pcm"

.globl PCM_NEW_polarbear_warning1
.globl _PCM_NEW_polarbear_warning1
PCM_NEW_polarbear_warning1:
_PCM_NEW_polarbear_warning1:
.incbin "assets/sound/pcm/polarbear_warning1.pcm"

.globl PCM_NEW_polarbear_warning2
.globl _PCM_NEW_polarbear_warning2
PCM_NEW_polarbear_warning2:
_PCM_NEW_polarbear_warning2:
.incbin "assets/sound/pcm/polarbear_warning2.pcm"

.globl PCM_NEW_polarbear_warning3
.globl _PCM_NEW_polarbear_warning3
PCM_NEW_polarbear_warning3:
_PCM_NEW_polarbear_warning3:
.incbin "assets/sound/pcm/polarbear_warning3.pcm"

.globl PCM_NEW_armor_equip_chain1
.globl _PCM_NEW_armor_equip_chain1
PCM_NEW_armor_equip_chain1:
_PCM_NEW_armor_equip_chain1:
.incbin "assets/sound/pcm/armor_equip_chain1.pcm"

.globl PCM_NEW_armor_equip_chain2
.globl _PCM_NEW_armor_equip_chain2
PCM_NEW_armor_equip_chain2:
_PCM_NEW_armor_equip_chain2:
.incbin "assets/sound/pcm/armor_equip_chain2.pcm"

.globl PCM_NEW_armor_equip_chain3
.globl _PCM_NEW_armor_equip_chain3
PCM_NEW_armor_equip_chain3:
_PCM_NEW_armor_equip_chain3:
.incbin "assets/sound/pcm/armor_equip_chain3.pcm"

.globl PCM_NEW_armor_equip_chain4
.globl _PCM_NEW_armor_equip_chain4
PCM_NEW_armor_equip_chain4:
_PCM_NEW_armor_equip_chain4:
.incbin "assets/sound/pcm/armor_equip_chain4.pcm"

.globl PCM_NEW_armor_equip_chain5
.globl _PCM_NEW_armor_equip_chain5
PCM_NEW_armor_equip_chain5:
_PCM_NEW_armor_equip_chain5:
.incbin "assets/sound/pcm/armor_equip_chain5.pcm"

.globl PCM_NEW_armor_equip_chain6
.globl _PCM_NEW_armor_equip_chain6
PCM_NEW_armor_equip_chain6:
_PCM_NEW_armor_equip_chain6:
.incbin "assets/sound/pcm/armor_equip_chain6.pcm"

.globl PCM_NEW_armor_equip_diamond1
.globl _PCM_NEW_armor_equip_diamond1
PCM_NEW_armor_equip_diamond1:
_PCM_NEW_armor_equip_diamond1:
.incbin "assets/sound/pcm/armor_equip_diamond1.pcm"

.globl PCM_NEW_armor_equip_diamond2
.globl _PCM_NEW_armor_equip_diamond2
PCM_NEW_armor_equip_diamond2:
_PCM_NEW_armor_equip_diamond2:
.incbin "assets/sound/pcm/armor_equip_diamond2.pcm"

.globl PCM_NEW_armor_equip_diamond3
.globl _PCM_NEW_armor_equip_diamond3
PCM_NEW_armor_equip_diamond3:
_PCM_NEW_armor_equip_diamond3:
.incbin "assets/sound/pcm/armor_equip_diamond3.pcm"

.globl PCM_NEW_armor_equip_diamond4
.globl _PCM_NEW_armor_equip_diamond4
PCM_NEW_armor_equip_diamond4:
_PCM_NEW_armor_equip_diamond4:
.incbin "assets/sound/pcm/armor_equip_diamond4.pcm"

.globl PCM_NEW_armor_equip_diamond5
.globl _PCM_NEW_armor_equip_diamond5
PCM_NEW_armor_equip_diamond5:
_PCM_NEW_armor_equip_diamond5:
.incbin "assets/sound/pcm/armor_equip_diamond5.pcm"

.globl PCM_NEW_armor_equip_diamond6
.globl _PCM_NEW_armor_equip_diamond6
PCM_NEW_armor_equip_diamond6:
_PCM_NEW_armor_equip_diamond6:
.incbin "assets/sound/pcm/armor_equip_diamond6.pcm"

.globl PCM_NEW_armor_equip_generic1
.globl _PCM_NEW_armor_equip_generic1
PCM_NEW_armor_equip_generic1:
_PCM_NEW_armor_equip_generic1:
.incbin "assets/sound/pcm/armor_equip_generic1.pcm"

.globl PCM_NEW_armor_equip_generic2
.globl _PCM_NEW_armor_equip_generic2
PCM_NEW_armor_equip_generic2:
_PCM_NEW_armor_equip_generic2:
.incbin "assets/sound/pcm/armor_equip_generic2.pcm"

.globl PCM_NEW_armor_equip_generic3
.globl _PCM_NEW_armor_equip_generic3
PCM_NEW_armor_equip_generic3:
_PCM_NEW_armor_equip_generic3:
.incbin "assets/sound/pcm/armor_equip_generic3.pcm"

.globl PCM_NEW_armor_equip_generic4
.globl _PCM_NEW_armor_equip_generic4
PCM_NEW_armor_equip_generic4:
_PCM_NEW_armor_equip_generic4:
.incbin "assets/sound/pcm/armor_equip_generic4.pcm"

.globl PCM_NEW_armor_equip_generic5
.globl _PCM_NEW_armor_equip_generic5
PCM_NEW_armor_equip_generic5:
_PCM_NEW_armor_equip_generic5:
.incbin "assets/sound/pcm/armor_equip_generic5.pcm"

.globl PCM_NEW_armor_equip_generic6
.globl _PCM_NEW_armor_equip_generic6
PCM_NEW_armor_equip_generic6:
_PCM_NEW_armor_equip_generic6:
.incbin "assets/sound/pcm/armor_equip_generic6.pcm"

.globl PCM_NEW_armor_equip_gold1
.globl _PCM_NEW_armor_equip_gold1
PCM_NEW_armor_equip_gold1:
_PCM_NEW_armor_equip_gold1:
.incbin "assets/sound/pcm/armor_equip_gold1.pcm"

.globl PCM_NEW_armor_equip_gold2
.globl _PCM_NEW_armor_equip_gold2
PCM_NEW_armor_equip_gold2:
_PCM_NEW_armor_equip_gold2:
.incbin "assets/sound/pcm/armor_equip_gold2.pcm"

.globl PCM_NEW_armor_equip_gold3
.globl _PCM_NEW_armor_equip_gold3
PCM_NEW_armor_equip_gold3:
_PCM_NEW_armor_equip_gold3:
.incbin "assets/sound/pcm/armor_equip_gold3.pcm"

.globl PCM_NEW_armor_equip_gold4
.globl _PCM_NEW_armor_equip_gold4
PCM_NEW_armor_equip_gold4:
_PCM_NEW_armor_equip_gold4:
.incbin "assets/sound/pcm/armor_equip_gold4.pcm"

.globl PCM_NEW_armor_equip_gold5
.globl _PCM_NEW_armor_equip_gold5
PCM_NEW_armor_equip_gold5:
_PCM_NEW_armor_equip_gold5:
.incbin "assets/sound/pcm/armor_equip_gold5.pcm"

.globl PCM_NEW_armor_equip_gold6
.globl _PCM_NEW_armor_equip_gold6
PCM_NEW_armor_equip_gold6:
_PCM_NEW_armor_equip_gold6:
.incbin "assets/sound/pcm/armor_equip_gold6.pcm"

.globl PCM_NEW_armor_equip_iron1
.globl _PCM_NEW_armor_equip_iron1
PCM_NEW_armor_equip_iron1:
_PCM_NEW_armor_equip_iron1:
.incbin "assets/sound/pcm/armor_equip_iron1.pcm"

.globl PCM_NEW_armor_equip_iron2
.globl _PCM_NEW_armor_equip_iron2
PCM_NEW_armor_equip_iron2:
_PCM_NEW_armor_equip_iron2:
.incbin "assets/sound/pcm/armor_equip_iron2.pcm"

.globl PCM_NEW_armor_equip_iron3
.globl _PCM_NEW_armor_equip_iron3
PCM_NEW_armor_equip_iron3:
_PCM_NEW_armor_equip_iron3:
.incbin "assets/sound/pcm/armor_equip_iron3.pcm"

.globl PCM_NEW_armor_equip_iron4
.globl _PCM_NEW_armor_equip_iron4
PCM_NEW_armor_equip_iron4:
_PCM_NEW_armor_equip_iron4:
.incbin "assets/sound/pcm/armor_equip_iron4.pcm"

.globl PCM_NEW_armor_equip_iron5
.globl _PCM_NEW_armor_equip_iron5
PCM_NEW_armor_equip_iron5:
_PCM_NEW_armor_equip_iron5:
.incbin "assets/sound/pcm/armor_equip_iron5.pcm"

.globl PCM_NEW_armor_equip_iron6
.globl _PCM_NEW_armor_equip_iron6
PCM_NEW_armor_equip_iron6:
_PCM_NEW_armor_equip_iron6:
.incbin "assets/sound/pcm/armor_equip_iron6.pcm"

.globl PCM_NEW_armor_equip_leather1
.globl _PCM_NEW_armor_equip_leather1
PCM_NEW_armor_equip_leather1:
_PCM_NEW_armor_equip_leather1:
.incbin "assets/sound/pcm/armor_equip_leather1.pcm"

.globl PCM_NEW_armor_equip_leather2
.globl _PCM_NEW_armor_equip_leather2
PCM_NEW_armor_equip_leather2:
_PCM_NEW_armor_equip_leather2:
.incbin "assets/sound/pcm/armor_equip_leather2.pcm"

.globl PCM_NEW_armor_equip_leather3
.globl _PCM_NEW_armor_equip_leather3
PCM_NEW_armor_equip_leather3:
_PCM_NEW_armor_equip_leather3:
.incbin "assets/sound/pcm/armor_equip_leather3.pcm"

.globl PCM_NEW_armor_equip_leather4
.globl _PCM_NEW_armor_equip_leather4
PCM_NEW_armor_equip_leather4:
_PCM_NEW_armor_equip_leather4:
.incbin "assets/sound/pcm/armor_equip_leather4.pcm"

.globl PCM_NEW_armor_equip_leather5
.globl _PCM_NEW_armor_equip_leather5
PCM_NEW_armor_equip_leather5:
_PCM_NEW_armor_equip_leather5:
.incbin "assets/sound/pcm/armor_equip_leather5.pcm"

.globl PCM_NEW_armor_equip_leather6
.globl _PCM_NEW_armor_equip_leather6
PCM_NEW_armor_equip_leather6:
_PCM_NEW_armor_equip_leather6:
.incbin "assets/sound/pcm/armor_equip_leather6.pcm"

.globl PCM_NEW_fox_aggro1
.globl _PCM_NEW_fox_aggro1
PCM_NEW_fox_aggro1:
_PCM_NEW_fox_aggro1:
.incbin "assets/sound/pcm/fox_aggro1.pcm"

.globl PCM_NEW_fox_aggro2
.globl _PCM_NEW_fox_aggro2
PCM_NEW_fox_aggro2:
_PCM_NEW_fox_aggro2:
.incbin "assets/sound/pcm/fox_aggro2.pcm"

.globl PCM_NEW_fox_aggro3
.globl _PCM_NEW_fox_aggro3
PCM_NEW_fox_aggro3:
_PCM_NEW_fox_aggro3:
.incbin "assets/sound/pcm/fox_aggro3.pcm"

.globl PCM_NEW_fox_aggro4
.globl _PCM_NEW_fox_aggro4
PCM_NEW_fox_aggro4:
_PCM_NEW_fox_aggro4:
.incbin "assets/sound/pcm/fox_aggro4.pcm"

.globl PCM_NEW_fox_aggro5
.globl _PCM_NEW_fox_aggro5
PCM_NEW_fox_aggro5:
_PCM_NEW_fox_aggro5:
.incbin "assets/sound/pcm/fox_aggro5.pcm"

.globl PCM_NEW_fox_aggro6
.globl _PCM_NEW_fox_aggro6
PCM_NEW_fox_aggro6:
_PCM_NEW_fox_aggro6:
.incbin "assets/sound/pcm/fox_aggro6.pcm"

.globl PCM_NEW_fox_aggro7
.globl _PCM_NEW_fox_aggro7
PCM_NEW_fox_aggro7:
_PCM_NEW_fox_aggro7:
.incbin "assets/sound/pcm/fox_aggro7.pcm"

.globl PCM_NEW_fox_bite1
.globl _PCM_NEW_fox_bite1
PCM_NEW_fox_bite1:
_PCM_NEW_fox_bite1:
.incbin "assets/sound/pcm/fox_bite1.pcm"

.globl PCM_NEW_fox_bite2
.globl _PCM_NEW_fox_bite2
PCM_NEW_fox_bite2:
_PCM_NEW_fox_bite2:
.incbin "assets/sound/pcm/fox_bite2.pcm"

.globl PCM_NEW_fox_bite3
.globl _PCM_NEW_fox_bite3
PCM_NEW_fox_bite3:
_PCM_NEW_fox_bite3:
.incbin "assets/sound/pcm/fox_bite3.pcm"

.globl PCM_NEW_fox_death1
.globl _PCM_NEW_fox_death1
PCM_NEW_fox_death1:
_PCM_NEW_fox_death1:
.incbin "assets/sound/pcm/fox_death1.pcm"

.globl PCM_NEW_fox_death2
.globl _PCM_NEW_fox_death2
PCM_NEW_fox_death2:
_PCM_NEW_fox_death2:
.incbin "assets/sound/pcm/fox_death2.pcm"

.globl PCM_NEW_fox_eat1
.globl _PCM_NEW_fox_eat1
PCM_NEW_fox_eat1:
_PCM_NEW_fox_eat1:
.incbin "assets/sound/pcm/fox_eat1.pcm"

.globl PCM_NEW_fox_eat2
.globl _PCM_NEW_fox_eat2
PCM_NEW_fox_eat2:
_PCM_NEW_fox_eat2:
.incbin "assets/sound/pcm/fox_eat2.pcm"

.globl PCM_NEW_fox_eat3
.globl _PCM_NEW_fox_eat3
PCM_NEW_fox_eat3:
_PCM_NEW_fox_eat3:
.incbin "assets/sound/pcm/fox_eat3.pcm"

.globl PCM_NEW_fox_hurt1
.globl _PCM_NEW_fox_hurt1
PCM_NEW_fox_hurt1:
_PCM_NEW_fox_hurt1:
.incbin "assets/sound/pcm/fox_hurt1.pcm"

.globl PCM_NEW_fox_hurt2
.globl _PCM_NEW_fox_hurt2
PCM_NEW_fox_hurt2:
_PCM_NEW_fox_hurt2:
.incbin "assets/sound/pcm/fox_hurt2.pcm"

.globl PCM_NEW_fox_hurt3
.globl _PCM_NEW_fox_hurt3
PCM_NEW_fox_hurt3:
_PCM_NEW_fox_hurt3:
.incbin "assets/sound/pcm/fox_hurt3.pcm"

.globl PCM_NEW_fox_hurt4
.globl _PCM_NEW_fox_hurt4
PCM_NEW_fox_hurt4:
_PCM_NEW_fox_hurt4:
.incbin "assets/sound/pcm/fox_hurt4.pcm"

.globl PCM_NEW_fox_idle1
.globl _PCM_NEW_fox_idle1
PCM_NEW_fox_idle1:
_PCM_NEW_fox_idle1:
.incbin "assets/sound/pcm/fox_idle1.pcm"

.globl PCM_NEW_fox_idle2
.globl _PCM_NEW_fox_idle2
PCM_NEW_fox_idle2:
_PCM_NEW_fox_idle2:
.incbin "assets/sound/pcm/fox_idle2.pcm"

.globl PCM_NEW_fox_idle3
.globl _PCM_NEW_fox_idle3
PCM_NEW_fox_idle3:
_PCM_NEW_fox_idle3:
.incbin "assets/sound/pcm/fox_idle3.pcm"

.globl PCM_NEW_fox_idle4
.globl _PCM_NEW_fox_idle4
PCM_NEW_fox_idle4:
_PCM_NEW_fox_idle4:
.incbin "assets/sound/pcm/fox_idle4.pcm"

.globl PCM_NEW_fox_idle5
.globl _PCM_NEW_fox_idle5
PCM_NEW_fox_idle5:
_PCM_NEW_fox_idle5:
.incbin "assets/sound/pcm/fox_idle5.pcm"

.globl PCM_NEW_fox_idle6
.globl _PCM_NEW_fox_idle6
PCM_NEW_fox_idle6:
_PCM_NEW_fox_idle6:
.incbin "assets/sound/pcm/fox_idle6.pcm"

.globl PCM_NEW_fox_screech1
.globl _PCM_NEW_fox_screech1
PCM_NEW_fox_screech1:
_PCM_NEW_fox_screech1:
.incbin "assets/sound/pcm/fox_screech1.pcm"

.globl PCM_NEW_fox_screech2
.globl _PCM_NEW_fox_screech2
PCM_NEW_fox_screech2:
_PCM_NEW_fox_screech2:
.incbin "assets/sound/pcm/fox_screech2.pcm"

.globl PCM_NEW_fox_screech3
.globl _PCM_NEW_fox_screech3
PCM_NEW_fox_screech3:
_PCM_NEW_fox_screech3:
.incbin "assets/sound/pcm/fox_screech3.pcm"

.globl PCM_NEW_fox_screech4
.globl _PCM_NEW_fox_screech4
PCM_NEW_fox_screech4:
_PCM_NEW_fox_screech4:
.incbin "assets/sound/pcm/fox_screech4.pcm"

.globl PCM_NEW_fox_sleep1
.globl _PCM_NEW_fox_sleep1
PCM_NEW_fox_sleep1:
_PCM_NEW_fox_sleep1:
.incbin "assets/sound/pcm/fox_sleep1.pcm"

.globl PCM_NEW_fox_sleep2
.globl _PCM_NEW_fox_sleep2
PCM_NEW_fox_sleep2:
_PCM_NEW_fox_sleep2:
.incbin "assets/sound/pcm/fox_sleep2.pcm"

.globl PCM_NEW_fox_sleep3
.globl _PCM_NEW_fox_sleep3
PCM_NEW_fox_sleep3:
_PCM_NEW_fox_sleep3:
.incbin "assets/sound/pcm/fox_sleep3.pcm"

.globl PCM_NEW_fox_sleep4
.globl _PCM_NEW_fox_sleep4
PCM_NEW_fox_sleep4:
_PCM_NEW_fox_sleep4:
.incbin "assets/sound/pcm/fox_sleep4.pcm"

.globl PCM_NEW_fox_sleep5
.globl _PCM_NEW_fox_sleep5
PCM_NEW_fox_sleep5:
_PCM_NEW_fox_sleep5:
.incbin "assets/sound/pcm/fox_sleep5.pcm"

.globl PCM_NEW_fox_sniff1
.globl _PCM_NEW_fox_sniff1
PCM_NEW_fox_sniff1:
_PCM_NEW_fox_sniff1:
.incbin "assets/sound/pcm/fox_sniff1.pcm"

.globl PCM_NEW_fox_sniff2
.globl _PCM_NEW_fox_sniff2
PCM_NEW_fox_sniff2:
_PCM_NEW_fox_sniff2:
.incbin "assets/sound/pcm/fox_sniff2.pcm"

.globl PCM_NEW_fox_sniff3
.globl _PCM_NEW_fox_sniff3
PCM_NEW_fox_sniff3:
_PCM_NEW_fox_sniff3:
.incbin "assets/sound/pcm/fox_sniff3.pcm"

.globl PCM_NEW_fox_sniff4
.globl _PCM_NEW_fox_sniff4
PCM_NEW_fox_sniff4:
_PCM_NEW_fox_sniff4:
.incbin "assets/sound/pcm/fox_sniff4.pcm"

.globl PCM_NEW_fox_spit1
.globl _PCM_NEW_fox_spit1
PCM_NEW_fox_spit1:
_PCM_NEW_fox_spit1:
.incbin "assets/sound/pcm/fox_spit1.pcm"

.globl PCM_NEW_fox_spit2
.globl _PCM_NEW_fox_spit2
PCM_NEW_fox_spit2:
_PCM_NEW_fox_spit2:
.incbin "assets/sound/pcm/fox_spit2.pcm"

.globl PCM_NEW_fox_spit3
.globl _PCM_NEW_fox_spit3
PCM_NEW_fox_spit3:
_PCM_NEW_fox_spit3:
.incbin "assets/sound/pcm/fox_spit3.pcm"

.globl PCM_NEW_silverfish_hit1
.globl _PCM_NEW_silverfish_hit1
PCM_NEW_silverfish_hit1:
_PCM_NEW_silverfish_hit1:
.incbin "assets/sound/pcm/silverfish_hit1.pcm"

.globl PCM_NEW_silverfish_hit2
.globl _PCM_NEW_silverfish_hit2
PCM_NEW_silverfish_hit2:
_PCM_NEW_silverfish_hit2:
.incbin "assets/sound/pcm/silverfish_hit2.pcm"

.globl PCM_NEW_silverfish_hit3
.globl _PCM_NEW_silverfish_hit3
PCM_NEW_silverfish_hit3:
_PCM_NEW_silverfish_hit3:
.incbin "assets/sound/pcm/silverfish_hit3.pcm"

.globl PCM_NEW_silverfish_kill
.globl _PCM_NEW_silverfish_kill
PCM_NEW_silverfish_kill:
_PCM_NEW_silverfish_kill:
.incbin "assets/sound/pcm/silverfish_kill.pcm"

.globl PCM_NEW_silverfish_say1
.globl _PCM_NEW_silverfish_say1
PCM_NEW_silverfish_say1:
_PCM_NEW_silverfish_say1:
.incbin "assets/sound/pcm/silverfish_say1.pcm"

.globl PCM_NEW_silverfish_say2
.globl _PCM_NEW_silverfish_say2
PCM_NEW_silverfish_say2:
_PCM_NEW_silverfish_say2:
.incbin "assets/sound/pcm/silverfish_say2.pcm"

.globl PCM_NEW_silverfish_say3
.globl _PCM_NEW_silverfish_say3
PCM_NEW_silverfish_say3:
_PCM_NEW_silverfish_say3:
.incbin "assets/sound/pcm/silverfish_say3.pcm"

.globl PCM_NEW_silverfish_say4
.globl _PCM_NEW_silverfish_say4
PCM_NEW_silverfish_say4:
_PCM_NEW_silverfish_say4:
.incbin "assets/sound/pcm/silverfish_say4.pcm"

.globl PCM_NEW_silverfish_step1
.globl _PCM_NEW_silverfish_step1
PCM_NEW_silverfish_step1:
_PCM_NEW_silverfish_step1:
.incbin "assets/sound/pcm/silverfish_step1.pcm"

.globl PCM_NEW_silverfish_step2
.globl _PCM_NEW_silverfish_step2
PCM_NEW_silverfish_step2:
_PCM_NEW_silverfish_step2:
.incbin "assets/sound/pcm/silverfish_step2.pcm"

.globl PCM_NEW_silverfish_step3
.globl _PCM_NEW_silverfish_step3
PCM_NEW_silverfish_step3:
_PCM_NEW_silverfish_step3:
.incbin "assets/sound/pcm/silverfish_step3.pcm"

.globl PCM_NEW_silverfish_step4
.globl _PCM_NEW_silverfish_step4
PCM_NEW_silverfish_step4:
_PCM_NEW_silverfish_step4:
.incbin "assets/sound/pcm/silverfish_step4.pcm"

.globl PCM_NEW_villager_idle1
.globl _PCM_NEW_villager_idle1
PCM_NEW_villager_idle1:
_PCM_NEW_villager_idle1:
.incbin "assets/sound/pcm/villager_idle1.pcm"

.globl PCM_NEW_villager_idle2
.globl _PCM_NEW_villager_idle2
PCM_NEW_villager_idle2:
_PCM_NEW_villager_idle2:
.incbin "assets/sound/pcm/villager_idle2.pcm"

.globl PCM_NEW_villager_idle3
.globl _PCM_NEW_villager_idle3
PCM_NEW_villager_idle3:
_PCM_NEW_villager_idle3:
.incbin "assets/sound/pcm/villager_idle3.pcm"

.globl PCM_NEW_villager_hit1
.globl _PCM_NEW_villager_hit1
PCM_NEW_villager_hit1:
_PCM_NEW_villager_hit1:
.incbin "assets/sound/pcm/villager_hit1.pcm"

.globl PCM_NEW_villager_hit2
.globl _PCM_NEW_villager_hit2
PCM_NEW_villager_hit2:
_PCM_NEW_villager_hit2:
.incbin "assets/sound/pcm/villager_hit2.pcm"

.globl PCM_NEW_villager_hit3
.globl _PCM_NEW_villager_hit3
PCM_NEW_villager_hit3:
_PCM_NEW_villager_hit3:
.incbin "assets/sound/pcm/villager_hit3.pcm"

.globl PCM_NEW_villager_hit4
.globl _PCM_NEW_villager_hit4
PCM_NEW_villager_hit4:
_PCM_NEW_villager_hit4:
.incbin "assets/sound/pcm/villager_hit4.pcm"

.globl PCM_NEW_villager_death
.globl _PCM_NEW_villager_death
PCM_NEW_villager_death:
_PCM_NEW_villager_death:
.incbin "assets/sound/pcm/villager_death.pcm"

.globl PCM_NEW_villager_haggle1
.globl _PCM_NEW_villager_haggle1
PCM_NEW_villager_haggle1:
_PCM_NEW_villager_haggle1:
.incbin "assets/sound/pcm/villager_haggle1.pcm"

.globl PCM_NEW_villager_haggle2
.globl _PCM_NEW_villager_haggle2
PCM_NEW_villager_haggle2:
_PCM_NEW_villager_haggle2:
.incbin "assets/sound/pcm/villager_haggle2.pcm"

.globl PCM_NEW_villager_haggle3
.globl _PCM_NEW_villager_haggle3
PCM_NEW_villager_haggle3:
_PCM_NEW_villager_haggle3:
.incbin "assets/sound/pcm/villager_haggle3.pcm"

.globl PCM_NEW_villager_yes1
.globl _PCM_NEW_villager_yes1
PCM_NEW_villager_yes1:
_PCM_NEW_villager_yes1:
.incbin "assets/sound/pcm/villager_yes1.pcm"

.globl PCM_NEW_villager_yes2
.globl _PCM_NEW_villager_yes2
PCM_NEW_villager_yes2:
_PCM_NEW_villager_yes2:
.incbin "assets/sound/pcm/villager_yes2.pcm"

.globl PCM_NEW_villager_yes3
.globl _PCM_NEW_villager_yes3
PCM_NEW_villager_yes3:
_PCM_NEW_villager_yes3:
.incbin "assets/sound/pcm/villager_yes3.pcm"

.globl PCM_NEW_villager_no1
.globl _PCM_NEW_villager_no1
PCM_NEW_villager_no1:
_PCM_NEW_villager_no1:
.incbin "assets/sound/pcm/villager_no1.pcm"

.globl PCM_NEW_villager_no2
.globl _PCM_NEW_villager_no2
PCM_NEW_villager_no2:
_PCM_NEW_villager_no2:
.incbin "assets/sound/pcm/villager_no2.pcm"

.globl PCM_NEW_villager_no3
.globl _PCM_NEW_villager_no3
PCM_NEW_villager_no3:
_PCM_NEW_villager_no3:
.incbin "assets/sound/pcm/villager_no3.pcm"

.globl PCM_NEW_sweet_berry_bush_break1
.globl _PCM_NEW_sweet_berry_bush_break1
PCM_NEW_sweet_berry_bush_break1:
_PCM_NEW_sweet_berry_bush_break1:
.incbin "assets/sound/pcm/sweet_berry_bush_break1.pcm"

.globl PCM_NEW_sweet_berry_bush_break2
.globl _PCM_NEW_sweet_berry_bush_break2
PCM_NEW_sweet_berry_bush_break2:
_PCM_NEW_sweet_berry_bush_break2:
.incbin "assets/sound/pcm/sweet_berry_bush_break2.pcm"

.globl PCM_NEW_sweet_berry_bush_break3
.globl _PCM_NEW_sweet_berry_bush_break3
PCM_NEW_sweet_berry_bush_break3:
_PCM_NEW_sweet_berry_bush_break3:
.incbin "assets/sound/pcm/sweet_berry_bush_break3.pcm"

.globl PCM_NEW_sweet_berry_bush_break4
.globl _PCM_NEW_sweet_berry_bush_break4
PCM_NEW_sweet_berry_bush_break4:
_PCM_NEW_sweet_berry_bush_break4:
.incbin "assets/sound/pcm/sweet_berry_bush_break4.pcm"

.globl PCM_NEW_sweet_berry_bush_pick_from_bush1
.globl _PCM_NEW_sweet_berry_bush_pick_from_bush1
PCM_NEW_sweet_berry_bush_pick_from_bush1:
_PCM_NEW_sweet_berry_bush_pick_from_bush1:
.incbin "assets/sound/pcm/sweet_berry_bush_pick_from_bush1.pcm"

.globl PCM_NEW_sweet_berry_bush_pick_from_bush2
.globl _PCM_NEW_sweet_berry_bush_pick_from_bush2
PCM_NEW_sweet_berry_bush_pick_from_bush2:
_PCM_NEW_sweet_berry_bush_pick_from_bush2:
.incbin "assets/sound/pcm/sweet_berry_bush_pick_from_bush2.pcm"

.globl PCM_NEW_sweet_berry_bush_place1
.globl _PCM_NEW_sweet_berry_bush_place1
PCM_NEW_sweet_berry_bush_place1:
_PCM_NEW_sweet_berry_bush_place1:
.incbin "assets/sound/pcm/sweet_berry_bush_place1.pcm"

.globl PCM_NEW_sweet_berry_bush_place2
.globl _PCM_NEW_sweet_berry_bush_place2
PCM_NEW_sweet_berry_bush_place2:
_PCM_NEW_sweet_berry_bush_place2:
.incbin "assets/sound/pcm/sweet_berry_bush_place2.pcm"

.globl PCM_NEW_sweet_berry_bush_place3
.globl _PCM_NEW_sweet_berry_bush_place3
PCM_NEW_sweet_berry_bush_place3:
_PCM_NEW_sweet_berry_bush_place3:
.incbin "assets/sound/pcm/sweet_berry_bush_place3.pcm"

.globl PCM_NEW_sweet_berry_bush_place4
.globl _PCM_NEW_sweet_berry_bush_place4
PCM_NEW_sweet_berry_bush_place4:
_PCM_NEW_sweet_berry_bush_place4:
.incbin "assets/sound/pcm/sweet_berry_bush_place4.pcm"

.globl PCM_NEW_sweet_berry_bush_place5
.globl _PCM_NEW_sweet_berry_bush_place5
PCM_NEW_sweet_berry_bush_place5:
_PCM_NEW_sweet_berry_bush_place5:
.incbin "assets/sound/pcm/sweet_berry_bush_place5.pcm"

.globl PCM_NEW_sweet_berry_bush_place6
.globl _PCM_NEW_sweet_berry_bush_place6
PCM_NEW_sweet_berry_bush_place6:
_PCM_NEW_sweet_berry_bush_place6:
.incbin "assets/sound/pcm/sweet_berry_bush_place6.pcm"


