#include <sound/NewSoundData.hpp>
#include <sound/SoundRepository.hpp>
#include <sound/SoundDesc.hpp>

extern "C" {
extern uint8_t PCM_NEW_weather_rain1[];
extern uint8_t PCM_NEW_weather_rain2[];
extern uint8_t PCM_NEW_weather_rain3[];
extern uint8_t PCM_NEW_weather_rain4[];
extern uint8_t PCM_NEW_weather_rain5[];
extern uint8_t PCM_NEW_weather_rain6[];
extern uint8_t PCM_NEW_weather_rain7[];
extern uint8_t PCM_NEW_weather_rain8[];
extern uint8_t PCM_NEW_weather_thunder1[];
extern uint8_t PCM_NEW_weather_thunder2[];
extern uint8_t PCM_NEW_weather_thunder3[];
extern uint8_t PCM_NEW_fish_flop1[];
extern uint8_t PCM_NEW_fish_flop2[];
extern uint8_t PCM_NEW_fish_flop3[];
extern uint8_t PCM_NEW_fish_flop4[];
extern uint8_t PCM_NEW_fish_hurt1[];
extern uint8_t PCM_NEW_fish_hurt2[];
extern uint8_t PCM_NEW_fish_hurt3[];
extern uint8_t PCM_NEW_fish_hurt4[];
extern uint8_t PCM_NEW_fish_swim1[];
extern uint8_t PCM_NEW_fish_swim2[];
extern uint8_t PCM_NEW_fish_swim3[];
extern uint8_t PCM_NEW_fish_swim4[];
extern uint8_t PCM_NEW_fish_swim5[];
extern uint8_t PCM_NEW_fish_swim6[];
extern uint8_t PCM_NEW_fish_swim7[];
extern uint8_t PCM_NEW_turtle_armor[];
extern uint8_t PCM_NEW_turtle_death1[];
extern uint8_t PCM_NEW_turtle_death2[];
extern uint8_t PCM_NEW_turtle_death3[];
extern uint8_t PCM_NEW_turtle_hurt1[];
extern uint8_t PCM_NEW_turtle_hurt2[];
extern uint8_t PCM_NEW_turtle_hurt3[];
extern uint8_t PCM_NEW_turtle_hurt4[];
extern uint8_t PCM_NEW_turtle_hurt5[];
extern uint8_t PCM_NEW_turtle_idle1[];
extern uint8_t PCM_NEW_turtle_idle2[];
extern uint8_t PCM_NEW_turtle_idle3[];
extern uint8_t PCM_NEW_turtle_walk1[];
extern uint8_t PCM_NEW_turtle_walk2[];
extern uint8_t PCM_NEW_turtle_walk3[];
extern uint8_t PCM_NEW_turtle_walk4[];
extern uint8_t PCM_NEW_turtle_walk5[];
extern uint8_t PCM_NEW_turtle_egg_drop_egg1[];
extern uint8_t PCM_NEW_turtle_egg_drop_egg2[];
extern uint8_t PCM_NEW_turtle_egg_egg_break1[];
extern uint8_t PCM_NEW_turtle_egg_egg_break2[];
extern uint8_t PCM_NEW_turtle_egg_egg_crack1[];
extern uint8_t PCM_NEW_turtle_egg_egg_crack2[];
extern uint8_t PCM_NEW_turtle_egg_egg_crack3[];
extern uint8_t PCM_NEW_turtle_egg_egg_crack4[];
extern uint8_t PCM_NEW_turtle_egg_egg_crack5[];
extern uint8_t PCM_NEW_turtle_egg_jump_egg1[];
extern uint8_t PCM_NEW_turtle_egg_jump_egg2[];
extern uint8_t PCM_NEW_turtle_egg_jump_egg3[];
extern uint8_t PCM_NEW_turtle_egg_jump_egg4[];
extern uint8_t PCM_NEW_turtle_swim_swim1[];
extern uint8_t PCM_NEW_turtle_swim_swim2[];
extern uint8_t PCM_NEW_turtle_swim_swim3[];
extern uint8_t PCM_NEW_turtle_swim_swim4[];
extern uint8_t PCM_NEW_turtle_swim_swim5[];
extern uint8_t PCM_NEW_turtle_baby_death1[];
extern uint8_t PCM_NEW_turtle_baby_death2[];
extern uint8_t PCM_NEW_turtle_baby_egg_hatched1[];
extern uint8_t PCM_NEW_turtle_baby_egg_hatched2[];
extern uint8_t PCM_NEW_turtle_baby_egg_hatched3[];
extern uint8_t PCM_NEW_turtle_baby_hurt1[];
extern uint8_t PCM_NEW_turtle_baby_hurt2[];
extern uint8_t PCM_NEW_turtle_baby_shamble1[];
extern uint8_t PCM_NEW_turtle_baby_shamble2[];
extern uint8_t PCM_NEW_turtle_baby_shamble3[];
extern uint8_t PCM_NEW_turtle_baby_shamble4[];
extern uint8_t PCM_NEW_wolf_bark1[];
extern uint8_t PCM_NEW_wolf_bark2[];
extern uint8_t PCM_NEW_wolf_bark3[];
extern uint8_t PCM_NEW_wolf_death[];
extern uint8_t PCM_NEW_wolf_growl1[];
extern uint8_t PCM_NEW_wolf_growl2[];
extern uint8_t PCM_NEW_wolf_growl3[];
extern uint8_t PCM_NEW_wolf_howl1[];
extern uint8_t PCM_NEW_wolf_howl2[];
extern uint8_t PCM_NEW_wolf_hurt1[];
extern uint8_t PCM_NEW_wolf_hurt2[];
extern uint8_t PCM_NEW_wolf_hurt3[];
extern uint8_t PCM_NEW_wolf_panting[];
extern uint8_t PCM_NEW_wolf_shake[];
extern uint8_t PCM_NEW_wolf_step1[];
extern uint8_t PCM_NEW_wolf_step2[];
extern uint8_t PCM_NEW_wolf_step3[];
extern uint8_t PCM_NEW_wolf_step4[];
extern uint8_t PCM_NEW_wolf_step5[];
extern uint8_t PCM_NEW_wolf_whine[];
extern uint8_t PCM_NEW_slime_attack1[];
extern uint8_t PCM_NEW_slime_attack2[];
extern uint8_t PCM_NEW_slime_big1[];
extern uint8_t PCM_NEW_slime_big2[];
extern uint8_t PCM_NEW_slime_big3[];
extern uint8_t PCM_NEW_slime_big4[];
extern uint8_t PCM_NEW_slime_small1[];
extern uint8_t PCM_NEW_slime_small2[];
extern uint8_t PCM_NEW_slime_small3[];
extern uint8_t PCM_NEW_slime_small4[];
extern uint8_t PCM_NEW_slime_small5[];
extern uint8_t PCM_NEW_water_heavy_splash[];
extern uint8_t PCM_NEW_water_lava[];
extern uint8_t PCM_NEW_water_lavapop[];
extern uint8_t PCM_NEW_water_splash[];
extern uint8_t PCM_NEW_water_splash2[];
extern uint8_t PCM_NEW_water_swim1[];
extern uint8_t PCM_NEW_water_swim10[];
extern uint8_t PCM_NEW_water_swim11[];
extern uint8_t PCM_NEW_water_swim12[];
extern uint8_t PCM_NEW_water_swim13[];
extern uint8_t PCM_NEW_water_swim14[];
extern uint8_t PCM_NEW_water_swim15[];
extern uint8_t PCM_NEW_water_swim16[];
extern uint8_t PCM_NEW_water_swim17[];
extern uint8_t PCM_NEW_water_swim18[];
extern uint8_t PCM_NEW_water_swim2[];
extern uint8_t PCM_NEW_water_swim3[];
extern uint8_t PCM_NEW_water_swim4[];
extern uint8_t PCM_NEW_water_swim5[];
extern uint8_t PCM_NEW_water_swim6[];
extern uint8_t PCM_NEW_water_swim7[];
extern uint8_t PCM_NEW_water_swim8[];
extern uint8_t PCM_NEW_water_swim9[];
extern uint8_t PCM_NEW_water_water[];
extern uint8_t PCM_NEW_pufferfish_blow_out1[];
extern uint8_t PCM_NEW_pufferfish_blow_out2[];
extern uint8_t PCM_NEW_pufferfish_blow_up1[];
extern uint8_t PCM_NEW_pufferfish_blow_up2[];
extern uint8_t PCM_NEW_pufferfish_death1[];
extern uint8_t PCM_NEW_pufferfish_death2[];
extern uint8_t PCM_NEW_pufferfish_flop1[];
extern uint8_t PCM_NEW_pufferfish_flop2[];
extern uint8_t PCM_NEW_pufferfish_flop3[];
extern uint8_t PCM_NEW_pufferfish_flop4[];
extern uint8_t PCM_NEW_pufferfish_hurt1[];
extern uint8_t PCM_NEW_pufferfish_hurt2[];
extern uint8_t PCM_NEW_pufferfish_sting1[];
extern uint8_t PCM_NEW_pufferfish_sting2[];
extern uint8_t PCM_NEW_squid_ambient1[];
extern uint8_t PCM_NEW_squid_ambient2[];
extern uint8_t PCM_NEW_squid_ambient3[];
extern uint8_t PCM_NEW_squid_ambient4[];
extern uint8_t PCM_NEW_squid_ambient5[];
extern uint8_t PCM_NEW_squid_death1[];
extern uint8_t PCM_NEW_squid_death2[];
extern uint8_t PCM_NEW_squid_death3[];
extern uint8_t PCM_NEW_squid_hurt1[];
extern uint8_t PCM_NEW_squid_hurt2[];
extern uint8_t PCM_NEW_squid_hurt3[];
extern uint8_t PCM_NEW_squid_hurt4[];
extern uint8_t PCM_NEW_squid_squirt1[];
extern uint8_t PCM_NEW_squid_squirt2[];
extern uint8_t PCM_NEW_squid_squirt3[];
extern uint8_t PCM_NEW_polarbear_death1[];
extern uint8_t PCM_NEW_polarbear_death2[];
extern uint8_t PCM_NEW_polarbear_death3[];
extern uint8_t PCM_NEW_polarbear_hurt1[];
extern uint8_t PCM_NEW_polarbear_hurt2[];
extern uint8_t PCM_NEW_polarbear_hurt3[];
extern uint8_t PCM_NEW_polarbear_hurt4[];
extern uint8_t PCM_NEW_polarbear_idle1[];
extern uint8_t PCM_NEW_polarbear_idle2[];
extern uint8_t PCM_NEW_polarbear_idle3[];
extern uint8_t PCM_NEW_polarbear_idle4[];
extern uint8_t PCM_NEW_polarbear_step1[];
extern uint8_t PCM_NEW_polarbear_step2[];
extern uint8_t PCM_NEW_polarbear_step3[];
extern uint8_t PCM_NEW_polarbear_step4[];
extern uint8_t PCM_NEW_polarbear_warning1[];
extern uint8_t PCM_NEW_polarbear_warning2[];
extern uint8_t PCM_NEW_polarbear_warning3[];
extern uint8_t PCM_NEW_armor_equip_chain1[];
extern uint8_t PCM_NEW_armor_equip_chain2[];
extern uint8_t PCM_NEW_armor_equip_chain3[];
extern uint8_t PCM_NEW_armor_equip_chain4[];
extern uint8_t PCM_NEW_armor_equip_chain5[];
extern uint8_t PCM_NEW_armor_equip_chain6[];
extern uint8_t PCM_NEW_armor_equip_diamond1[];
extern uint8_t PCM_NEW_armor_equip_diamond2[];
extern uint8_t PCM_NEW_armor_equip_diamond3[];
extern uint8_t PCM_NEW_armor_equip_diamond4[];
extern uint8_t PCM_NEW_armor_equip_diamond5[];
extern uint8_t PCM_NEW_armor_equip_diamond6[];
extern uint8_t PCM_NEW_armor_equip_generic1[];
extern uint8_t PCM_NEW_armor_equip_generic2[];
extern uint8_t PCM_NEW_armor_equip_generic3[];
extern uint8_t PCM_NEW_armor_equip_generic4[];
extern uint8_t PCM_NEW_armor_equip_generic5[];
extern uint8_t PCM_NEW_armor_equip_generic6[];
extern uint8_t PCM_NEW_armor_equip_gold1[];
extern uint8_t PCM_NEW_armor_equip_gold2[];
extern uint8_t PCM_NEW_armor_equip_gold3[];
extern uint8_t PCM_NEW_armor_equip_gold4[];
extern uint8_t PCM_NEW_armor_equip_gold5[];
extern uint8_t PCM_NEW_armor_equip_gold6[];
extern uint8_t PCM_NEW_armor_equip_iron1[];
extern uint8_t PCM_NEW_armor_equip_iron2[];
extern uint8_t PCM_NEW_armor_equip_iron3[];
extern uint8_t PCM_NEW_armor_equip_iron4[];
extern uint8_t PCM_NEW_armor_equip_iron5[];
extern uint8_t PCM_NEW_armor_equip_iron6[];
extern uint8_t PCM_NEW_armor_equip_leather1[];
extern uint8_t PCM_NEW_armor_equip_leather2[];
extern uint8_t PCM_NEW_armor_equip_leather3[];
extern uint8_t PCM_NEW_armor_equip_leather4[];
extern uint8_t PCM_NEW_armor_equip_leather5[];
extern uint8_t PCM_NEW_armor_equip_leather6[];
extern uint8_t PCM_NEW_fox_aggro1[];
extern uint8_t PCM_NEW_fox_aggro2[];
extern uint8_t PCM_NEW_fox_aggro3[];
extern uint8_t PCM_NEW_fox_aggro4[];
extern uint8_t PCM_NEW_fox_aggro5[];
extern uint8_t PCM_NEW_fox_aggro6[];
extern uint8_t PCM_NEW_fox_aggro7[];
extern uint8_t PCM_NEW_fox_bite1[];
extern uint8_t PCM_NEW_fox_bite2[];
extern uint8_t PCM_NEW_fox_bite3[];
extern uint8_t PCM_NEW_fox_death1[];
extern uint8_t PCM_NEW_fox_death2[];
extern uint8_t PCM_NEW_fox_eat1[];
extern uint8_t PCM_NEW_fox_eat2[];
extern uint8_t PCM_NEW_fox_eat3[];
extern uint8_t PCM_NEW_fox_hurt1[];
extern uint8_t PCM_NEW_fox_hurt2[];
extern uint8_t PCM_NEW_fox_hurt3[];
extern uint8_t PCM_NEW_fox_hurt4[];
extern uint8_t PCM_NEW_fox_idle1[];
extern uint8_t PCM_NEW_fox_idle2[];
extern uint8_t PCM_NEW_fox_idle3[];
extern uint8_t PCM_NEW_fox_idle4[];
extern uint8_t PCM_NEW_fox_idle5[];
extern uint8_t PCM_NEW_fox_idle6[];
extern uint8_t PCM_NEW_fox_screech1[];
extern uint8_t PCM_NEW_fox_screech2[];
extern uint8_t PCM_NEW_fox_screech3[];
extern uint8_t PCM_NEW_fox_screech4[];
extern uint8_t PCM_NEW_fox_sleep1[];
extern uint8_t PCM_NEW_fox_sleep2[];
extern uint8_t PCM_NEW_fox_sleep3[];
extern uint8_t PCM_NEW_fox_sleep4[];
extern uint8_t PCM_NEW_fox_sleep5[];
extern uint8_t PCM_NEW_fox_sniff1[];
extern uint8_t PCM_NEW_fox_sniff2[];
extern uint8_t PCM_NEW_fox_sniff3[];
extern uint8_t PCM_NEW_fox_sniff4[];
extern uint8_t PCM_NEW_fox_spit1[];
extern uint8_t PCM_NEW_fox_spit2[];
extern uint8_t PCM_NEW_fox_spit3[];
extern uint8_t PCM_NEW_silverfish_hit1[];
extern uint8_t PCM_NEW_silverfish_hit2[];
extern uint8_t PCM_NEW_silverfish_hit3[];
extern uint8_t PCM_NEW_silverfish_kill[];
extern uint8_t PCM_NEW_silverfish_say1[];
extern uint8_t PCM_NEW_silverfish_say2[];
extern uint8_t PCM_NEW_silverfish_say3[];
extern uint8_t PCM_NEW_silverfish_say4[];
extern uint8_t PCM_NEW_silverfish_step1[];
extern uint8_t PCM_NEW_silverfish_step2[];
extern uint8_t PCM_NEW_silverfish_step3[];
extern uint8_t PCM_NEW_silverfish_step4[];
extern uint8_t PCM_NEW_villager_idle1[];
extern uint8_t PCM_NEW_villager_idle2[];
extern uint8_t PCM_NEW_villager_idle3[];
extern uint8_t PCM_NEW_villager_hit1[];
extern uint8_t PCM_NEW_villager_hit2[];
extern uint8_t PCM_NEW_villager_hit3[];
extern uint8_t PCM_NEW_villager_hit4[];
extern uint8_t PCM_NEW_villager_death[];
extern uint8_t PCM_NEW_villager_haggle1[];
extern uint8_t PCM_NEW_villager_haggle2[];
extern uint8_t PCM_NEW_villager_haggle3[];
extern uint8_t PCM_NEW_villager_yes1[];
extern uint8_t PCM_NEW_villager_yes2[];
extern uint8_t PCM_NEW_villager_yes3[];
extern uint8_t PCM_NEW_villager_no1[];
extern uint8_t PCM_NEW_villager_no2[];
extern uint8_t PCM_NEW_villager_no3[];
extern uint8_t PCM_NEW_sweet_berry_bush_break1[];
extern uint8_t PCM_NEW_sweet_berry_bush_break2[];
extern uint8_t PCM_NEW_sweet_berry_bush_break3[];
extern uint8_t PCM_NEW_sweet_berry_bush_break4[];
extern uint8_t PCM_NEW_sweet_berry_bush_pick_from_bush1[];
extern uint8_t PCM_NEW_sweet_berry_bush_pick_from_bush2[];
extern uint8_t PCM_NEW_sweet_berry_bush_place1[];
extern uint8_t PCM_NEW_sweet_berry_bush_place2[];
extern uint8_t PCM_NEW_sweet_berry_bush_place3[];
extern uint8_t PCM_NEW_sweet_berry_bush_place4[];
extern uint8_t PCM_NEW_sweet_berry_bush_place5[];
extern uint8_t PCM_NEW_sweet_berry_bush_place6[];
}

static SoundDesc SA_NEW_weather_rain1((char_t*)PCM_NEW_weather_rain1);
static SoundDesc SA_NEW_weather_rain2((char_t*)PCM_NEW_weather_rain2);
static SoundDesc SA_NEW_weather_rain3((char_t*)PCM_NEW_weather_rain3);
static SoundDesc SA_NEW_weather_rain4((char_t*)PCM_NEW_weather_rain4);
static SoundDesc SA_NEW_weather_rain5((char_t*)PCM_NEW_weather_rain5);
static SoundDesc SA_NEW_weather_rain6((char_t*)PCM_NEW_weather_rain6);
static SoundDesc SA_NEW_weather_rain7((char_t*)PCM_NEW_weather_rain7);
static SoundDesc SA_NEW_weather_rain8((char_t*)PCM_NEW_weather_rain8);
static SoundDesc SA_NEW_weather_thunder1((char_t*)PCM_NEW_weather_thunder1);
static SoundDesc SA_NEW_weather_thunder2((char_t*)PCM_NEW_weather_thunder2);
static SoundDesc SA_NEW_weather_thunder3((char_t*)PCM_NEW_weather_thunder3);
static SoundDesc SA_NEW_fish_flop1((char_t*)PCM_NEW_fish_flop1);
static SoundDesc SA_NEW_fish_flop2((char_t*)PCM_NEW_fish_flop2);
static SoundDesc SA_NEW_fish_flop3((char_t*)PCM_NEW_fish_flop3);
static SoundDesc SA_NEW_fish_flop4((char_t*)PCM_NEW_fish_flop4);
static SoundDesc SA_NEW_fish_hurt1((char_t*)PCM_NEW_fish_hurt1);
static SoundDesc SA_NEW_fish_hurt2((char_t*)PCM_NEW_fish_hurt2);
static SoundDesc SA_NEW_fish_hurt3((char_t*)PCM_NEW_fish_hurt3);
static SoundDesc SA_NEW_fish_hurt4((char_t*)PCM_NEW_fish_hurt4);
static SoundDesc SA_NEW_fish_swim1((char_t*)PCM_NEW_fish_swim1);
static SoundDesc SA_NEW_fish_swim2((char_t*)PCM_NEW_fish_swim2);
static SoundDesc SA_NEW_fish_swim3((char_t*)PCM_NEW_fish_swim3);
static SoundDesc SA_NEW_fish_swim4((char_t*)PCM_NEW_fish_swim4);
static SoundDesc SA_NEW_fish_swim5((char_t*)PCM_NEW_fish_swim5);
static SoundDesc SA_NEW_fish_swim6((char_t*)PCM_NEW_fish_swim6);
static SoundDesc SA_NEW_fish_swim7((char_t*)PCM_NEW_fish_swim7);
static SoundDesc SA_NEW_turtle_armor((char_t*)PCM_NEW_turtle_armor);
static SoundDesc SA_NEW_turtle_death1((char_t*)PCM_NEW_turtle_death1);
static SoundDesc SA_NEW_turtle_death2((char_t*)PCM_NEW_turtle_death2);
static SoundDesc SA_NEW_turtle_death3((char_t*)PCM_NEW_turtle_death3);
static SoundDesc SA_NEW_turtle_hurt1((char_t*)PCM_NEW_turtle_hurt1);
static SoundDesc SA_NEW_turtle_hurt2((char_t*)PCM_NEW_turtle_hurt2);
static SoundDesc SA_NEW_turtle_hurt3((char_t*)PCM_NEW_turtle_hurt3);
static SoundDesc SA_NEW_turtle_hurt4((char_t*)PCM_NEW_turtle_hurt4);
static SoundDesc SA_NEW_turtle_hurt5((char_t*)PCM_NEW_turtle_hurt5);
static SoundDesc SA_NEW_turtle_idle1((char_t*)PCM_NEW_turtle_idle1);
static SoundDesc SA_NEW_turtle_idle2((char_t*)PCM_NEW_turtle_idle2);
static SoundDesc SA_NEW_turtle_idle3((char_t*)PCM_NEW_turtle_idle3);
static SoundDesc SA_NEW_turtle_walk1((char_t*)PCM_NEW_turtle_walk1);
static SoundDesc SA_NEW_turtle_walk2((char_t*)PCM_NEW_turtle_walk2);
static SoundDesc SA_NEW_turtle_walk3((char_t*)PCM_NEW_turtle_walk3);
static SoundDesc SA_NEW_turtle_walk4((char_t*)PCM_NEW_turtle_walk4);
static SoundDesc SA_NEW_turtle_walk5((char_t*)PCM_NEW_turtle_walk5);
static SoundDesc SA_NEW_turtle_egg_drop_egg1((char_t*)PCM_NEW_turtle_egg_drop_egg1);
static SoundDesc SA_NEW_turtle_egg_drop_egg2((char_t*)PCM_NEW_turtle_egg_drop_egg2);
static SoundDesc SA_NEW_turtle_egg_egg_break1((char_t*)PCM_NEW_turtle_egg_egg_break1);
static SoundDesc SA_NEW_turtle_egg_egg_break2((char_t*)PCM_NEW_turtle_egg_egg_break2);
static SoundDesc SA_NEW_turtle_egg_egg_crack1((char_t*)PCM_NEW_turtle_egg_egg_crack1);
static SoundDesc SA_NEW_turtle_egg_egg_crack2((char_t*)PCM_NEW_turtle_egg_egg_crack2);
static SoundDesc SA_NEW_turtle_egg_egg_crack3((char_t*)PCM_NEW_turtle_egg_egg_crack3);
static SoundDesc SA_NEW_turtle_egg_egg_crack4((char_t*)PCM_NEW_turtle_egg_egg_crack4);
static SoundDesc SA_NEW_turtle_egg_egg_crack5((char_t*)PCM_NEW_turtle_egg_egg_crack5);
static SoundDesc SA_NEW_turtle_egg_jump_egg1((char_t*)PCM_NEW_turtle_egg_jump_egg1);
static SoundDesc SA_NEW_turtle_egg_jump_egg2((char_t*)PCM_NEW_turtle_egg_jump_egg2);
static SoundDesc SA_NEW_turtle_egg_jump_egg3((char_t*)PCM_NEW_turtle_egg_jump_egg3);
static SoundDesc SA_NEW_turtle_egg_jump_egg4((char_t*)PCM_NEW_turtle_egg_jump_egg4);
static SoundDesc SA_NEW_turtle_swim_swim1((char_t*)PCM_NEW_turtle_swim_swim1);
static SoundDesc SA_NEW_turtle_swim_swim2((char_t*)PCM_NEW_turtle_swim_swim2);
static SoundDesc SA_NEW_turtle_swim_swim3((char_t*)PCM_NEW_turtle_swim_swim3);
static SoundDesc SA_NEW_turtle_swim_swim4((char_t*)PCM_NEW_turtle_swim_swim4);
static SoundDesc SA_NEW_turtle_swim_swim5((char_t*)PCM_NEW_turtle_swim_swim5);
static SoundDesc SA_NEW_turtle_baby_death1((char_t*)PCM_NEW_turtle_baby_death1);
static SoundDesc SA_NEW_turtle_baby_death2((char_t*)PCM_NEW_turtle_baby_death2);
static SoundDesc SA_NEW_turtle_baby_egg_hatched1((char_t*)PCM_NEW_turtle_baby_egg_hatched1);
static SoundDesc SA_NEW_turtle_baby_egg_hatched2((char_t*)PCM_NEW_turtle_baby_egg_hatched2);
static SoundDesc SA_NEW_turtle_baby_egg_hatched3((char_t*)PCM_NEW_turtle_baby_egg_hatched3);
static SoundDesc SA_NEW_turtle_baby_hurt1((char_t*)PCM_NEW_turtle_baby_hurt1);
static SoundDesc SA_NEW_turtle_baby_hurt2((char_t*)PCM_NEW_turtle_baby_hurt2);
static SoundDesc SA_NEW_turtle_baby_shamble1((char_t*)PCM_NEW_turtle_baby_shamble1);
static SoundDesc SA_NEW_turtle_baby_shamble2((char_t*)PCM_NEW_turtle_baby_shamble2);
static SoundDesc SA_NEW_turtle_baby_shamble3((char_t*)PCM_NEW_turtle_baby_shamble3);
static SoundDesc SA_NEW_turtle_baby_shamble4((char_t*)PCM_NEW_turtle_baby_shamble4);
static SoundDesc SA_NEW_wolf_bark1((char_t*)PCM_NEW_wolf_bark1);
static SoundDesc SA_NEW_wolf_bark2((char_t*)PCM_NEW_wolf_bark2);
static SoundDesc SA_NEW_wolf_bark3((char_t*)PCM_NEW_wolf_bark3);
static SoundDesc SA_NEW_wolf_death((char_t*)PCM_NEW_wolf_death);
static SoundDesc SA_NEW_wolf_growl1((char_t*)PCM_NEW_wolf_growl1);
static SoundDesc SA_NEW_wolf_growl2((char_t*)PCM_NEW_wolf_growl2);
static SoundDesc SA_NEW_wolf_growl3((char_t*)PCM_NEW_wolf_growl3);
static SoundDesc SA_NEW_wolf_howl1((char_t*)PCM_NEW_wolf_howl1);
static SoundDesc SA_NEW_wolf_howl2((char_t*)PCM_NEW_wolf_howl2);
static SoundDesc SA_NEW_wolf_hurt1((char_t*)PCM_NEW_wolf_hurt1);
static SoundDesc SA_NEW_wolf_hurt2((char_t*)PCM_NEW_wolf_hurt2);
static SoundDesc SA_NEW_wolf_hurt3((char_t*)PCM_NEW_wolf_hurt3);
static SoundDesc SA_NEW_wolf_panting((char_t*)PCM_NEW_wolf_panting);
static SoundDesc SA_NEW_wolf_shake((char_t*)PCM_NEW_wolf_shake);
static SoundDesc SA_NEW_wolf_step1((char_t*)PCM_NEW_wolf_step1);
static SoundDesc SA_NEW_wolf_step2((char_t*)PCM_NEW_wolf_step2);
static SoundDesc SA_NEW_wolf_step3((char_t*)PCM_NEW_wolf_step3);
static SoundDesc SA_NEW_wolf_step4((char_t*)PCM_NEW_wolf_step4);
static SoundDesc SA_NEW_wolf_step5((char_t*)PCM_NEW_wolf_step5);
static SoundDesc SA_NEW_wolf_whine((char_t*)PCM_NEW_wolf_whine);
static SoundDesc SA_NEW_slime_attack1((char_t*)PCM_NEW_slime_attack1);
static SoundDesc SA_NEW_slime_attack2((char_t*)PCM_NEW_slime_attack2);
static SoundDesc SA_NEW_slime_big1((char_t*)PCM_NEW_slime_big1);
static SoundDesc SA_NEW_slime_big2((char_t*)PCM_NEW_slime_big2);
static SoundDesc SA_NEW_slime_big3((char_t*)PCM_NEW_slime_big3);
static SoundDesc SA_NEW_slime_big4((char_t*)PCM_NEW_slime_big4);
static SoundDesc SA_NEW_slime_small1((char_t*)PCM_NEW_slime_small1);
static SoundDesc SA_NEW_slime_small2((char_t*)PCM_NEW_slime_small2);
static SoundDesc SA_NEW_slime_small3((char_t*)PCM_NEW_slime_small3);
static SoundDesc SA_NEW_slime_small4((char_t*)PCM_NEW_slime_small4);
static SoundDesc SA_NEW_slime_small5((char_t*)PCM_NEW_slime_small5);
static SoundDesc SA_NEW_water_heavy_splash((char_t*)PCM_NEW_water_heavy_splash);
static SoundDesc SA_NEW_water_lava((char_t*)PCM_NEW_water_lava);
static SoundDesc SA_NEW_water_lavapop((char_t*)PCM_NEW_water_lavapop);
static SoundDesc SA_NEW_water_splash((char_t*)PCM_NEW_water_splash);
static SoundDesc SA_NEW_water_splash2((char_t*)PCM_NEW_water_splash2);
static SoundDesc SA_NEW_water_swim1((char_t*)PCM_NEW_water_swim1);
static SoundDesc SA_NEW_water_swim10((char_t*)PCM_NEW_water_swim10);
static SoundDesc SA_NEW_water_swim11((char_t*)PCM_NEW_water_swim11);
static SoundDesc SA_NEW_water_swim12((char_t*)PCM_NEW_water_swim12);
static SoundDesc SA_NEW_water_swim13((char_t*)PCM_NEW_water_swim13);
static SoundDesc SA_NEW_water_swim14((char_t*)PCM_NEW_water_swim14);
static SoundDesc SA_NEW_water_swim15((char_t*)PCM_NEW_water_swim15);
static SoundDesc SA_NEW_water_swim16((char_t*)PCM_NEW_water_swim16);
static SoundDesc SA_NEW_water_swim17((char_t*)PCM_NEW_water_swim17);
static SoundDesc SA_NEW_water_swim18((char_t*)PCM_NEW_water_swim18);
static SoundDesc SA_NEW_water_swim2((char_t*)PCM_NEW_water_swim2);
static SoundDesc SA_NEW_water_swim3((char_t*)PCM_NEW_water_swim3);
static SoundDesc SA_NEW_water_swim4((char_t*)PCM_NEW_water_swim4);
static SoundDesc SA_NEW_water_swim5((char_t*)PCM_NEW_water_swim5);
static SoundDesc SA_NEW_water_swim6((char_t*)PCM_NEW_water_swim6);
static SoundDesc SA_NEW_water_swim7((char_t*)PCM_NEW_water_swim7);
static SoundDesc SA_NEW_water_swim8((char_t*)PCM_NEW_water_swim8);
static SoundDesc SA_NEW_water_swim9((char_t*)PCM_NEW_water_swim9);
static SoundDesc SA_NEW_water_water((char_t*)PCM_NEW_water_water);
static SoundDesc SA_NEW_pufferfish_blow_out1((char_t*)PCM_NEW_pufferfish_blow_out1);
static SoundDesc SA_NEW_pufferfish_blow_out2((char_t*)PCM_NEW_pufferfish_blow_out2);
static SoundDesc SA_NEW_pufferfish_blow_up1((char_t*)PCM_NEW_pufferfish_blow_up1);
static SoundDesc SA_NEW_pufferfish_blow_up2((char_t*)PCM_NEW_pufferfish_blow_up2);
static SoundDesc SA_NEW_pufferfish_death1((char_t*)PCM_NEW_pufferfish_death1);
static SoundDesc SA_NEW_pufferfish_death2((char_t*)PCM_NEW_pufferfish_death2);
static SoundDesc SA_NEW_pufferfish_flop1((char_t*)PCM_NEW_pufferfish_flop1);
static SoundDesc SA_NEW_pufferfish_flop2((char_t*)PCM_NEW_pufferfish_flop2);
static SoundDesc SA_NEW_pufferfish_flop3((char_t*)PCM_NEW_pufferfish_flop3);
static SoundDesc SA_NEW_pufferfish_flop4((char_t*)PCM_NEW_pufferfish_flop4);
static SoundDesc SA_NEW_pufferfish_hurt1((char_t*)PCM_NEW_pufferfish_hurt1);
static SoundDesc SA_NEW_pufferfish_hurt2((char_t*)PCM_NEW_pufferfish_hurt2);
static SoundDesc SA_NEW_pufferfish_sting1((char_t*)PCM_NEW_pufferfish_sting1);
static SoundDesc SA_NEW_pufferfish_sting2((char_t*)PCM_NEW_pufferfish_sting2);
static SoundDesc SA_NEW_squid_ambient1((char_t*)PCM_NEW_squid_ambient1);
static SoundDesc SA_NEW_squid_ambient2((char_t*)PCM_NEW_squid_ambient2);
static SoundDesc SA_NEW_squid_ambient3((char_t*)PCM_NEW_squid_ambient3);
static SoundDesc SA_NEW_squid_ambient4((char_t*)PCM_NEW_squid_ambient4);
static SoundDesc SA_NEW_squid_ambient5((char_t*)PCM_NEW_squid_ambient5);
static SoundDesc SA_NEW_squid_death1((char_t*)PCM_NEW_squid_death1);
static SoundDesc SA_NEW_squid_death2((char_t*)PCM_NEW_squid_death2);
static SoundDesc SA_NEW_squid_death3((char_t*)PCM_NEW_squid_death3);
static SoundDesc SA_NEW_squid_hurt1((char_t*)PCM_NEW_squid_hurt1);
static SoundDesc SA_NEW_squid_hurt2((char_t*)PCM_NEW_squid_hurt2);
static SoundDesc SA_NEW_squid_hurt3((char_t*)PCM_NEW_squid_hurt3);
static SoundDesc SA_NEW_squid_hurt4((char_t*)PCM_NEW_squid_hurt4);
static SoundDesc SA_NEW_squid_squirt1((char_t*)PCM_NEW_squid_squirt1);
static SoundDesc SA_NEW_squid_squirt2((char_t*)PCM_NEW_squid_squirt2);
static SoundDesc SA_NEW_squid_squirt3((char_t*)PCM_NEW_squid_squirt3);
static SoundDesc SA_NEW_polarbear_death1((char_t*)PCM_NEW_polarbear_death1);
static SoundDesc SA_NEW_polarbear_death2((char_t*)PCM_NEW_polarbear_death2);
static SoundDesc SA_NEW_polarbear_death3((char_t*)PCM_NEW_polarbear_death3);
static SoundDesc SA_NEW_polarbear_hurt1((char_t*)PCM_NEW_polarbear_hurt1);
static SoundDesc SA_NEW_polarbear_hurt2((char_t*)PCM_NEW_polarbear_hurt2);
static SoundDesc SA_NEW_polarbear_hurt3((char_t*)PCM_NEW_polarbear_hurt3);
static SoundDesc SA_NEW_polarbear_hurt4((char_t*)PCM_NEW_polarbear_hurt4);
static SoundDesc SA_NEW_polarbear_idle1((char_t*)PCM_NEW_polarbear_idle1);
static SoundDesc SA_NEW_polarbear_idle2((char_t*)PCM_NEW_polarbear_idle2);
static SoundDesc SA_NEW_polarbear_idle3((char_t*)PCM_NEW_polarbear_idle3);
static SoundDesc SA_NEW_polarbear_idle4((char_t*)PCM_NEW_polarbear_idle4);
static SoundDesc SA_NEW_polarbear_step1((char_t*)PCM_NEW_polarbear_step1);
static SoundDesc SA_NEW_polarbear_step2((char_t*)PCM_NEW_polarbear_step2);
static SoundDesc SA_NEW_polarbear_step3((char_t*)PCM_NEW_polarbear_step3);
static SoundDesc SA_NEW_polarbear_step4((char_t*)PCM_NEW_polarbear_step4);
static SoundDesc SA_NEW_polarbear_warning1((char_t*)PCM_NEW_polarbear_warning1);
static SoundDesc SA_NEW_polarbear_warning2((char_t*)PCM_NEW_polarbear_warning2);
static SoundDesc SA_NEW_polarbear_warning3((char_t*)PCM_NEW_polarbear_warning3);
static SoundDesc SA_NEW_armor_equip_chain1((char_t*)PCM_NEW_armor_equip_chain1);
static SoundDesc SA_NEW_armor_equip_chain2((char_t*)PCM_NEW_armor_equip_chain2);
static SoundDesc SA_NEW_armor_equip_chain3((char_t*)PCM_NEW_armor_equip_chain3);
static SoundDesc SA_NEW_armor_equip_chain4((char_t*)PCM_NEW_armor_equip_chain4);
static SoundDesc SA_NEW_armor_equip_chain5((char_t*)PCM_NEW_armor_equip_chain5);
static SoundDesc SA_NEW_armor_equip_chain6((char_t*)PCM_NEW_armor_equip_chain6);
static SoundDesc SA_NEW_armor_equip_diamond1((char_t*)PCM_NEW_armor_equip_diamond1);
static SoundDesc SA_NEW_armor_equip_diamond2((char_t*)PCM_NEW_armor_equip_diamond2);
static SoundDesc SA_NEW_armor_equip_diamond3((char_t*)PCM_NEW_armor_equip_diamond3);
static SoundDesc SA_NEW_armor_equip_diamond4((char_t*)PCM_NEW_armor_equip_diamond4);
static SoundDesc SA_NEW_armor_equip_diamond5((char_t*)PCM_NEW_armor_equip_diamond5);
static SoundDesc SA_NEW_armor_equip_diamond6((char_t*)PCM_NEW_armor_equip_diamond6);
static SoundDesc SA_NEW_armor_equip_generic1((char_t*)PCM_NEW_armor_equip_generic1);
static SoundDesc SA_NEW_armor_equip_generic2((char_t*)PCM_NEW_armor_equip_generic2);
static SoundDesc SA_NEW_armor_equip_generic3((char_t*)PCM_NEW_armor_equip_generic3);
static SoundDesc SA_NEW_armor_equip_generic4((char_t*)PCM_NEW_armor_equip_generic4);
static SoundDesc SA_NEW_armor_equip_generic5((char_t*)PCM_NEW_armor_equip_generic5);
static SoundDesc SA_NEW_armor_equip_generic6((char_t*)PCM_NEW_armor_equip_generic6);
static SoundDesc SA_NEW_armor_equip_gold1((char_t*)PCM_NEW_armor_equip_gold1);
static SoundDesc SA_NEW_armor_equip_gold2((char_t*)PCM_NEW_armor_equip_gold2);
static SoundDesc SA_NEW_armor_equip_gold3((char_t*)PCM_NEW_armor_equip_gold3);
static SoundDesc SA_NEW_armor_equip_gold4((char_t*)PCM_NEW_armor_equip_gold4);
static SoundDesc SA_NEW_armor_equip_gold5((char_t*)PCM_NEW_armor_equip_gold5);
static SoundDesc SA_NEW_armor_equip_gold6((char_t*)PCM_NEW_armor_equip_gold6);
static SoundDesc SA_NEW_armor_equip_iron1((char_t*)PCM_NEW_armor_equip_iron1);
static SoundDesc SA_NEW_armor_equip_iron2((char_t*)PCM_NEW_armor_equip_iron2);
static SoundDesc SA_NEW_armor_equip_iron3((char_t*)PCM_NEW_armor_equip_iron3);
static SoundDesc SA_NEW_armor_equip_iron4((char_t*)PCM_NEW_armor_equip_iron4);
static SoundDesc SA_NEW_armor_equip_iron5((char_t*)PCM_NEW_armor_equip_iron5);
static SoundDesc SA_NEW_armor_equip_iron6((char_t*)PCM_NEW_armor_equip_iron6);
static SoundDesc SA_NEW_armor_equip_leather1((char_t*)PCM_NEW_armor_equip_leather1);
static SoundDesc SA_NEW_armor_equip_leather2((char_t*)PCM_NEW_armor_equip_leather2);
static SoundDesc SA_NEW_armor_equip_leather3((char_t*)PCM_NEW_armor_equip_leather3);
static SoundDesc SA_NEW_armor_equip_leather4((char_t*)PCM_NEW_armor_equip_leather4);
static SoundDesc SA_NEW_armor_equip_leather5((char_t*)PCM_NEW_armor_equip_leather5);
static SoundDesc SA_NEW_armor_equip_leather6((char_t*)PCM_NEW_armor_equip_leather6);
static SoundDesc SA_NEW_fox_aggro1((char_t*)PCM_NEW_fox_aggro1);
static SoundDesc SA_NEW_fox_aggro2((char_t*)PCM_NEW_fox_aggro2);
static SoundDesc SA_NEW_fox_aggro3((char_t*)PCM_NEW_fox_aggro3);
static SoundDesc SA_NEW_fox_aggro4((char_t*)PCM_NEW_fox_aggro4);
static SoundDesc SA_NEW_fox_aggro5((char_t*)PCM_NEW_fox_aggro5);
static SoundDesc SA_NEW_fox_aggro6((char_t*)PCM_NEW_fox_aggro6);
static SoundDesc SA_NEW_fox_aggro7((char_t*)PCM_NEW_fox_aggro7);
static SoundDesc SA_NEW_fox_bite1((char_t*)PCM_NEW_fox_bite1);
static SoundDesc SA_NEW_fox_bite2((char_t*)PCM_NEW_fox_bite2);
static SoundDesc SA_NEW_fox_bite3((char_t*)PCM_NEW_fox_bite3);
static SoundDesc SA_NEW_fox_death1((char_t*)PCM_NEW_fox_death1);
static SoundDesc SA_NEW_fox_death2((char_t*)PCM_NEW_fox_death2);
static SoundDesc SA_NEW_fox_eat1((char_t*)PCM_NEW_fox_eat1);
static SoundDesc SA_NEW_fox_eat2((char_t*)PCM_NEW_fox_eat2);
static SoundDesc SA_NEW_fox_eat3((char_t*)PCM_NEW_fox_eat3);
static SoundDesc SA_NEW_fox_hurt1((char_t*)PCM_NEW_fox_hurt1);
static SoundDesc SA_NEW_fox_hurt2((char_t*)PCM_NEW_fox_hurt2);
static SoundDesc SA_NEW_fox_hurt3((char_t*)PCM_NEW_fox_hurt3);
static SoundDesc SA_NEW_fox_hurt4((char_t*)PCM_NEW_fox_hurt4);
static SoundDesc SA_NEW_fox_idle1((char_t*)PCM_NEW_fox_idle1);
static SoundDesc SA_NEW_fox_idle2((char_t*)PCM_NEW_fox_idle2);
static SoundDesc SA_NEW_fox_idle3((char_t*)PCM_NEW_fox_idle3);
static SoundDesc SA_NEW_fox_idle4((char_t*)PCM_NEW_fox_idle4);
static SoundDesc SA_NEW_fox_idle5((char_t*)PCM_NEW_fox_idle5);
static SoundDesc SA_NEW_fox_idle6((char_t*)PCM_NEW_fox_idle6);
static SoundDesc SA_NEW_fox_screech1((char_t*)PCM_NEW_fox_screech1);
static SoundDesc SA_NEW_fox_screech2((char_t*)PCM_NEW_fox_screech2);
static SoundDesc SA_NEW_fox_screech3((char_t*)PCM_NEW_fox_screech3);
static SoundDesc SA_NEW_fox_screech4((char_t*)PCM_NEW_fox_screech4);
static SoundDesc SA_NEW_fox_sleep1((char_t*)PCM_NEW_fox_sleep1);
static SoundDesc SA_NEW_fox_sleep2((char_t*)PCM_NEW_fox_sleep2);
static SoundDesc SA_NEW_fox_sleep3((char_t*)PCM_NEW_fox_sleep3);
static SoundDesc SA_NEW_fox_sleep4((char_t*)PCM_NEW_fox_sleep4);
static SoundDesc SA_NEW_fox_sleep5((char_t*)PCM_NEW_fox_sleep5);
static SoundDesc SA_NEW_fox_sniff1((char_t*)PCM_NEW_fox_sniff1);
static SoundDesc SA_NEW_fox_sniff2((char_t*)PCM_NEW_fox_sniff2);
static SoundDesc SA_NEW_fox_sniff3((char_t*)PCM_NEW_fox_sniff3);
static SoundDesc SA_NEW_fox_sniff4((char_t*)PCM_NEW_fox_sniff4);
static SoundDesc SA_NEW_fox_spit1((char_t*)PCM_NEW_fox_spit1);
static SoundDesc SA_NEW_fox_spit2((char_t*)PCM_NEW_fox_spit2);
static SoundDesc SA_NEW_fox_spit3((char_t*)PCM_NEW_fox_spit3);
static SoundDesc SA_NEW_silverfish_hit1((char_t*)PCM_NEW_silverfish_hit1);
static SoundDesc SA_NEW_silverfish_hit2((char_t*)PCM_NEW_silverfish_hit2);
static SoundDesc SA_NEW_silverfish_hit3((char_t*)PCM_NEW_silverfish_hit3);
static SoundDesc SA_NEW_silverfish_kill((char_t*)PCM_NEW_silverfish_kill);
static SoundDesc SA_NEW_silverfish_say1((char_t*)PCM_NEW_silverfish_say1);
static SoundDesc SA_NEW_silverfish_say2((char_t*)PCM_NEW_silverfish_say2);
static SoundDesc SA_NEW_silverfish_say3((char_t*)PCM_NEW_silverfish_say3);
static SoundDesc SA_NEW_silverfish_say4((char_t*)PCM_NEW_silverfish_say4);
static SoundDesc SA_NEW_silverfish_step1((char_t*)PCM_NEW_silverfish_step1);
static SoundDesc SA_NEW_silverfish_step2((char_t*)PCM_NEW_silverfish_step2);
static SoundDesc SA_NEW_silverfish_step3((char_t*)PCM_NEW_silverfish_step3);
static SoundDesc SA_NEW_silverfish_step4((char_t*)PCM_NEW_silverfish_step4);
static SoundDesc SA_NEW_villager_idle1((char_t*)PCM_NEW_villager_idle1);
static SoundDesc SA_NEW_villager_idle2((char_t*)PCM_NEW_villager_idle2);
static SoundDesc SA_NEW_villager_idle3((char_t*)PCM_NEW_villager_idle3);
static SoundDesc SA_NEW_villager_hit1((char_t*)PCM_NEW_villager_hit1);
static SoundDesc SA_NEW_villager_hit2((char_t*)PCM_NEW_villager_hit2);
static SoundDesc SA_NEW_villager_hit3((char_t*)PCM_NEW_villager_hit3);
static SoundDesc SA_NEW_villager_hit4((char_t*)PCM_NEW_villager_hit4);
static SoundDesc SA_NEW_villager_death((char_t*)PCM_NEW_villager_death);
static SoundDesc SA_NEW_villager_haggle1((char_t*)PCM_NEW_villager_haggle1);
static SoundDesc SA_NEW_villager_haggle2((char_t*)PCM_NEW_villager_haggle2);
static SoundDesc SA_NEW_villager_haggle3((char_t*)PCM_NEW_villager_haggle3);
static SoundDesc SA_NEW_villager_yes1((char_t*)PCM_NEW_villager_yes1);
static SoundDesc SA_NEW_villager_yes2((char_t*)PCM_NEW_villager_yes2);
static SoundDesc SA_NEW_villager_yes3((char_t*)PCM_NEW_villager_yes3);
static SoundDesc SA_NEW_villager_no1((char_t*)PCM_NEW_villager_no1);
static SoundDesc SA_NEW_villager_no2((char_t*)PCM_NEW_villager_no2);
static SoundDesc SA_NEW_villager_no3((char_t*)PCM_NEW_villager_no3);
static SoundDesc SA_NEW_sweet_berry_bush_break1((char_t*)PCM_NEW_sweet_berry_bush_break1);
static SoundDesc SA_NEW_sweet_berry_bush_break2((char_t*)PCM_NEW_sweet_berry_bush_break2);
static SoundDesc SA_NEW_sweet_berry_bush_break3((char_t*)PCM_NEW_sweet_berry_bush_break3);
static SoundDesc SA_NEW_sweet_berry_bush_break4((char_t*)PCM_NEW_sweet_berry_bush_break4);
static SoundDesc SA_NEW_sweet_berry_bush_pick1((char_t*)PCM_NEW_sweet_berry_bush_pick_from_bush1);
static SoundDesc SA_NEW_sweet_berry_bush_pick2((char_t*)PCM_NEW_sweet_berry_bush_pick_from_bush2);
static SoundDesc SA_NEW_sweet_berry_bush_place1((char_t*)PCM_NEW_sweet_berry_bush_place1);
static SoundDesc SA_NEW_sweet_berry_bush_place2((char_t*)PCM_NEW_sweet_berry_bush_place2);
static SoundDesc SA_NEW_sweet_berry_bush_place3((char_t*)PCM_NEW_sweet_berry_bush_place3);
static SoundDesc SA_NEW_sweet_berry_bush_place4((char_t*)PCM_NEW_sweet_berry_bush_place4);
static SoundDesc SA_NEW_sweet_berry_bush_place5((char_t*)PCM_NEW_sweet_berry_bush_place5);
static SoundDesc SA_NEW_sweet_berry_bush_place6((char_t*)PCM_NEW_sweet_berry_bush_place6);

void registerNewSounds(SoundRepository& repo) {
    repo.add("ambient.weather.rain", SA_NEW_weather_rain1);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain2);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain3);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain4);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain5);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain6);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain7);
    repo.add("ambient.weather.rain", SA_NEW_weather_rain8);
    repo.add("ambient.weather.thunder", SA_NEW_weather_thunder1);
    repo.add("ambient.weather.thunder", SA_NEW_weather_thunder2);
    repo.add("ambient.weather.thunder", SA_NEW_weather_thunder3);
    repo.add("mob.fish.flop", SA_NEW_fish_flop1);
    repo.add("mob.fish.flop", SA_NEW_fish_flop2);
    repo.add("mob.fish.flop", SA_NEW_fish_flop3);
    repo.add("mob.fish.flop", SA_NEW_fish_flop4);
    repo.add("mob.fish.hurt", SA_NEW_fish_hurt1);
    repo.add("mob.fish.hurt", SA_NEW_fish_hurt2);
    repo.add("mob.fish.hurt", SA_NEW_fish_hurt3);
    repo.add("mob.fish.hurt", SA_NEW_fish_hurt4);
    repo.add("mob.fish.swim", SA_NEW_fish_swim1);
    repo.add("mob.fish.swim", SA_NEW_fish_swim2);
    repo.add("mob.fish.swim", SA_NEW_fish_swim3);
    repo.add("mob.fish.swim", SA_NEW_fish_swim4);
    repo.add("mob.fish.swim", SA_NEW_fish_swim5);
    repo.add("mob.fish.swim", SA_NEW_fish_swim6);
    repo.add("mob.fish.swim", SA_NEW_fish_swim7);
    repo.add("mob.turtle.armor", SA_NEW_turtle_armor);
    repo.add("mob.turtle.death", SA_NEW_turtle_death1);
    repo.add("mob.turtle.death", SA_NEW_turtle_death2);
    repo.add("mob.turtle.death", SA_NEW_turtle_death3);
    repo.add("mob.turtle.hurt", SA_NEW_turtle_hurt1);
    repo.add("mob.turtle.hurt", SA_NEW_turtle_hurt2);
    repo.add("mob.turtle.hurt", SA_NEW_turtle_hurt3);
    repo.add("mob.turtle.hurt", SA_NEW_turtle_hurt4);
    repo.add("mob.turtle.hurt", SA_NEW_turtle_hurt5);
    repo.add("mob.turtle.idle", SA_NEW_turtle_idle1);
    repo.add("mob.turtle", SA_NEW_turtle_idle1);
    repo.add("mob.turtle.idle", SA_NEW_turtle_idle2);
    repo.add("mob.turtle", SA_NEW_turtle_idle2);
    repo.add("mob.turtle.idle", SA_NEW_turtle_idle3);
    repo.add("mob.turtle", SA_NEW_turtle_idle3);
    repo.add("mob.turtle.walk", SA_NEW_turtle_walk1);
    repo.add("mob.turtle.walk", SA_NEW_turtle_walk2);
    repo.add("mob.turtle.walk", SA_NEW_turtle_walk3);
    repo.add("mob.turtle.walk", SA_NEW_turtle_walk4);
    repo.add("mob.turtle.walk", SA_NEW_turtle_walk5);
    repo.add("mob.turtle.egg.drop_egg", SA_NEW_turtle_egg_drop_egg1);
    repo.add("mob.turtle.egg.drop_egg", SA_NEW_turtle_egg_drop_egg2);
    repo.add("mob.turtle.egg.egg_break", SA_NEW_turtle_egg_egg_break1);
    repo.add("mob.turtle.egg.egg_break", SA_NEW_turtle_egg_egg_break2);
    repo.add("mob.turtle.egg.egg_crack", SA_NEW_turtle_egg_egg_crack1);
    repo.add("mob.turtle.egg.egg_crack", SA_NEW_turtle_egg_egg_crack2);
    repo.add("mob.turtle.egg.egg_crack", SA_NEW_turtle_egg_egg_crack3);
    repo.add("mob.turtle.egg.egg_crack", SA_NEW_turtle_egg_egg_crack4);
    repo.add("mob.turtle.egg.egg_crack", SA_NEW_turtle_egg_egg_crack5);
    repo.add("mob.turtle.egg.jump_egg", SA_NEW_turtle_egg_jump_egg1);
    repo.add("mob.turtle.egg.jump_egg", SA_NEW_turtle_egg_jump_egg2);
    repo.add("mob.turtle.egg.jump_egg", SA_NEW_turtle_egg_jump_egg3);
    repo.add("mob.turtle.egg.jump_egg", SA_NEW_turtle_egg_jump_egg4);
    repo.add("mob.turtle.swim", SA_NEW_turtle_swim_swim1);
    repo.add("mob.turtle.swim", SA_NEW_turtle_swim_swim2);
    repo.add("mob.turtle.swim", SA_NEW_turtle_swim_swim3);
    repo.add("mob.turtle.swim", SA_NEW_turtle_swim_swim4);
    repo.add("mob.turtle.swim", SA_NEW_turtle_swim_swim5);
    repo.add("mob.turtle_baby.death", SA_NEW_turtle_baby_death1);
    repo.add("mob.turtle_baby.death", SA_NEW_turtle_baby_death2);
    repo.add("mob.turtle_baby.egg_hatched", SA_NEW_turtle_baby_egg_hatched1);
    repo.add("mob.turtle_baby.egg_hatched", SA_NEW_turtle_baby_egg_hatched2);
    repo.add("mob.turtle_baby.egg_hatched", SA_NEW_turtle_baby_egg_hatched3);
    repo.add("mob.turtle_baby.hurt", SA_NEW_turtle_baby_hurt1);
    repo.add("mob.turtle_baby.hurt", SA_NEW_turtle_baby_hurt2);
    repo.add("mob.turtle_baby.shamble", SA_NEW_turtle_baby_shamble1);
    repo.add("mob.turtle_baby.shamble", SA_NEW_turtle_baby_shamble2);
    repo.add("mob.turtle_baby.shamble", SA_NEW_turtle_baby_shamble3);
    repo.add("mob.turtle_baby.shamble", SA_NEW_turtle_baby_shamble4);
    repo.add("mob.wolf.bark", SA_NEW_wolf_bark1);
    repo.add("mob.wolf.bark", SA_NEW_wolf_bark2);
    repo.add("mob.wolf.bark", SA_NEW_wolf_bark3);
    repo.add("mob.wolf.death", SA_NEW_wolf_death);
    repo.add("mob.wolf.growl", SA_NEW_wolf_growl1);
    repo.add("mob.wolf.growl", SA_NEW_wolf_growl2);
    repo.add("mob.wolf.growl", SA_NEW_wolf_growl3);
    repo.add("mob.wolf.howl", SA_NEW_wolf_howl1);
    repo.add("mob.wolf.howl", SA_NEW_wolf_howl2);
    repo.add("mob.wolf.hurt", SA_NEW_wolf_hurt1);
    repo.add("mob.wolf.hurt", SA_NEW_wolf_hurt2);
    repo.add("mob.wolf.hurt", SA_NEW_wolf_hurt3);
    repo.add("mob.wolf.panting", SA_NEW_wolf_panting);
    repo.add("mob.wolf.shake", SA_NEW_wolf_shake);
    repo.add("mob.wolf.step", SA_NEW_wolf_step1);
    repo.add("mob.wolf.step", SA_NEW_wolf_step2);
    repo.add("mob.wolf.step", SA_NEW_wolf_step3);
    repo.add("mob.wolf.step", SA_NEW_wolf_step4);
    repo.add("mob.wolf.step", SA_NEW_wolf_step5);
    repo.add("mob.wolf.whine", SA_NEW_wolf_whine);
    repo.add("mob.slime.attack", SA_NEW_slime_attack1);
    repo.add("mob.slime.attack", SA_NEW_slime_attack2);
    repo.add("mob.slime.big", SA_NEW_slime_big1);
    repo.add("mob.slime.big", SA_NEW_slime_big2);
    repo.add("mob.slime.big", SA_NEW_slime_big3);
    repo.add("mob.slime.big", SA_NEW_slime_big4);
    repo.add("mob.slime.small", SA_NEW_slime_small1);
    repo.add("mob.slime.small", SA_NEW_slime_small2);
    repo.add("mob.slime.small", SA_NEW_slime_small3);
    repo.add("mob.slime.small", SA_NEW_slime_small4);
    repo.add("mob.slime.small", SA_NEW_slime_small5);
    repo.add("mob.slime", SA_NEW_slime_big1);
    repo.add("mob.slime", SA_NEW_slime_big2);
    repo.add("mob.slime", SA_NEW_slime_small1);
    repo.add("mob.slime", SA_NEW_slime_small2);
    repo.add("random.splash", SA_NEW_water_heavy_splash);
    repo.add("liquid.splash", SA_NEW_water_heavy_splash);
    repo.add("liquid.lava", SA_NEW_water_lava);
    repo.add("liquid.lavapop", SA_NEW_water_lavapop);
    repo.add("random.splash", SA_NEW_water_splash);
    repo.add("liquid.splash", SA_NEW_water_splash);
    repo.add("random.splash", SA_NEW_water_splash2);
    repo.add("liquid.splash", SA_NEW_water_splash2);
    repo.add("liquid.swim", SA_NEW_water_swim1);
    repo.add("random.swim", SA_NEW_water_swim1);
    repo.add("liquid.swim", SA_NEW_water_swim10);
    repo.add("random.swim", SA_NEW_water_swim10);
    repo.add("liquid.swim", SA_NEW_water_swim11);
    repo.add("random.swim", SA_NEW_water_swim11);
    repo.add("liquid.swim", SA_NEW_water_swim12);
    repo.add("random.swim", SA_NEW_water_swim12);
    repo.add("liquid.swim", SA_NEW_water_swim13);
    repo.add("random.swim", SA_NEW_water_swim13);
    repo.add("liquid.swim", SA_NEW_water_swim14);
    repo.add("random.swim", SA_NEW_water_swim14);
    repo.add("liquid.swim", SA_NEW_water_swim15);
    repo.add("random.swim", SA_NEW_water_swim15);
    repo.add("liquid.swim", SA_NEW_water_swim16);
    repo.add("random.swim", SA_NEW_water_swim16);
    repo.add("liquid.swim", SA_NEW_water_swim17);
    repo.add("random.swim", SA_NEW_water_swim17);
    repo.add("liquid.swim", SA_NEW_water_swim18);
    repo.add("random.swim", SA_NEW_water_swim18);
    repo.add("liquid.swim", SA_NEW_water_swim2);
    repo.add("random.swim", SA_NEW_water_swim2);
    repo.add("liquid.swim", SA_NEW_water_swim3);
    repo.add("random.swim", SA_NEW_water_swim3);
    repo.add("liquid.swim", SA_NEW_water_swim4);
    repo.add("random.swim", SA_NEW_water_swim4);
    repo.add("liquid.swim", SA_NEW_water_swim5);
    repo.add("random.swim", SA_NEW_water_swim5);
    repo.add("liquid.swim", SA_NEW_water_swim6);
    repo.add("random.swim", SA_NEW_water_swim6);
    repo.add("liquid.swim", SA_NEW_water_swim7);
    repo.add("random.swim", SA_NEW_water_swim7);
    repo.add("liquid.swim", SA_NEW_water_swim8);
    repo.add("random.swim", SA_NEW_water_swim8);
    repo.add("liquid.swim", SA_NEW_water_swim9);
    repo.add("random.swim", SA_NEW_water_swim9);
    repo.add("liquid.water", SA_NEW_water_water);
    repo.add("mob.pufferfish.blow_out", SA_NEW_pufferfish_blow_out1);
    repo.add("mob.pufferfish.blow_out", SA_NEW_pufferfish_blow_out2);
    repo.add("mob.pufferfish.blow_up", SA_NEW_pufferfish_blow_up1);
    repo.add("mob.pufferfish.blow_up", SA_NEW_pufferfish_blow_up2);
    repo.add("mob.pufferfish.death", SA_NEW_pufferfish_death1);
    repo.add("mob.pufferfish.death", SA_NEW_pufferfish_death2);
    repo.add("mob.pufferfish.flop", SA_NEW_pufferfish_flop1);
    repo.add("mob.pufferfish.flop", SA_NEW_pufferfish_flop2);
    repo.add("mob.pufferfish.flop", SA_NEW_pufferfish_flop3);
    repo.add("mob.pufferfish.flop", SA_NEW_pufferfish_flop4);
    repo.add("mob.pufferfish.hurt", SA_NEW_pufferfish_hurt1);
    repo.add("mob.pufferfish.hurt", SA_NEW_pufferfish_hurt2);
    repo.add("mob.pufferfish.sting", SA_NEW_pufferfish_sting1);
    repo.add("mob.pufferfish.sting", SA_NEW_pufferfish_sting2);
    repo.add("mob.squid.ambient", SA_NEW_squid_ambient1);
    repo.add("mob.squid", SA_NEW_squid_ambient1);
    repo.add("mob.squid.ambient", SA_NEW_squid_ambient2);
    repo.add("mob.squid", SA_NEW_squid_ambient2);
    repo.add("mob.squid.ambient", SA_NEW_squid_ambient3);
    repo.add("mob.squid", SA_NEW_squid_ambient3);
    repo.add("mob.squid.ambient", SA_NEW_squid_ambient4);
    repo.add("mob.squid", SA_NEW_squid_ambient4);
    repo.add("mob.squid.ambient", SA_NEW_squid_ambient5);
    repo.add("mob.squid", SA_NEW_squid_ambient5);
    repo.add("mob.squid.death", SA_NEW_squid_death1);
    repo.add("mob.squid.death", SA_NEW_squid_death2);
    repo.add("mob.squid.death", SA_NEW_squid_death3);
    repo.add("mob.squid.hurt", SA_NEW_squid_hurt1);
    repo.add("mob.squid.hurt", SA_NEW_squid_hurt2);
    repo.add("mob.squid.hurt", SA_NEW_squid_hurt3);
    repo.add("mob.squid.hurt", SA_NEW_squid_hurt4);
    repo.add("mob.squid.squirt", SA_NEW_squid_squirt1);
    repo.add("mob.squid.squirt", SA_NEW_squid_squirt2);
    repo.add("mob.squid.squirt", SA_NEW_squid_squirt3);
    repo.add("mob.polarbear.death", SA_NEW_polarbear_death1);
    repo.add("mob.polarbear.death", SA_NEW_polarbear_death2);
    repo.add("mob.polarbear.death", SA_NEW_polarbear_death3);
    repo.add("mob.polarbear.hurt", SA_NEW_polarbear_hurt1);
    repo.add("mob.polarbear.hurt", SA_NEW_polarbear_hurt2);
    repo.add("mob.polarbear.hurt", SA_NEW_polarbear_hurt3);
    repo.add("mob.polarbear.hurt", SA_NEW_polarbear_hurt4);
    repo.add("mob.polarbear.idle", SA_NEW_polarbear_idle1);
    repo.add("mob.polarbear", SA_NEW_polarbear_idle1);
    repo.add("mob.polarbear.idle", SA_NEW_polarbear_idle2);
    repo.add("mob.polarbear", SA_NEW_polarbear_idle2);
    repo.add("mob.polarbear.idle", SA_NEW_polarbear_idle3);
    repo.add("mob.polarbear", SA_NEW_polarbear_idle3);
    repo.add("mob.polarbear.idle", SA_NEW_polarbear_idle4);
    repo.add("mob.polarbear", SA_NEW_polarbear_idle4);
    repo.add("mob.polarbear.step", SA_NEW_polarbear_step1);
    repo.add("mob.polarbear.step", SA_NEW_polarbear_step2);
    repo.add("mob.polarbear.step", SA_NEW_polarbear_step3);
    repo.add("mob.polarbear.step", SA_NEW_polarbear_step4);
    repo.add("mob.polarbear.warning", SA_NEW_polarbear_warning1);
    repo.add("mob.polarbear.warning", SA_NEW_polarbear_warning2);
    repo.add("mob.polarbear.warning", SA_NEW_polarbear_warning3);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain1);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain2);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain3);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain4);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain5);
    repo.add("armor.equip_chain", SA_NEW_armor_equip_chain6);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond1);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond2);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond3);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond4);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond5);
    repo.add("armor.equip_diamond", SA_NEW_armor_equip_diamond6);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic1);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic2);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic3);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic4);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic5);
    repo.add("armor.equip_generic", SA_NEW_armor_equip_generic6);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold1);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold2);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold3);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold4);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold5);
    repo.add("armor.equip_gold", SA_NEW_armor_equip_gold6);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron1);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron2);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron3);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron4);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron5);
    repo.add("armor.equip_iron", SA_NEW_armor_equip_iron6);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather1);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather2);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather3);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather4);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather5);
    repo.add("armor.equip_leather", SA_NEW_armor_equip_leather6);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro1);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro2);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro3);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro4);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro5);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro6);
    repo.add("mob.fox.aggro", SA_NEW_fox_aggro7);
    repo.add("mob.fox.bite", SA_NEW_fox_bite1);
    repo.add("mob.fox.bite", SA_NEW_fox_bite2);
    repo.add("mob.fox.bite", SA_NEW_fox_bite3);
    repo.add("mob.fox.death", SA_NEW_fox_death1);
    repo.add("mob.fox.death", SA_NEW_fox_death2);
    repo.add("mob.fox.eat", SA_NEW_fox_eat1);
    repo.add("mob.fox.eat", SA_NEW_fox_eat2);
    repo.add("mob.fox.eat", SA_NEW_fox_eat3);
    repo.add("mob.fox.hurt", SA_NEW_fox_hurt1);
    repo.add("mob.fox.hurt", SA_NEW_fox_hurt2);
    repo.add("mob.fox.hurt", SA_NEW_fox_hurt3);
    repo.add("mob.fox.hurt", SA_NEW_fox_hurt4);
    repo.add("mob.fox.idle", SA_NEW_fox_idle1);
    repo.add("mob.fox", SA_NEW_fox_idle1);
    repo.add("mob.fox.idle", SA_NEW_fox_idle2);
    repo.add("mob.fox", SA_NEW_fox_idle2);
    repo.add("mob.fox.idle", SA_NEW_fox_idle3);
    repo.add("mob.fox", SA_NEW_fox_idle3);
    repo.add("mob.fox.idle", SA_NEW_fox_idle4);
    repo.add("mob.fox", SA_NEW_fox_idle4);
    repo.add("mob.fox.idle", SA_NEW_fox_idle5);
    repo.add("mob.fox", SA_NEW_fox_idle5);
    repo.add("mob.fox.idle", SA_NEW_fox_idle6);
    repo.add("mob.fox", SA_NEW_fox_idle6);
    repo.add("mob.fox.screech", SA_NEW_fox_screech1);
    repo.add("mob.fox.screech", SA_NEW_fox_screech2);
    repo.add("mob.fox.screech", SA_NEW_fox_screech3);
    repo.add("mob.fox.screech", SA_NEW_fox_screech4);
    repo.add("mob.fox.sleep", SA_NEW_fox_sleep1);
    repo.add("mob.fox.sleep", SA_NEW_fox_sleep2);
    repo.add("mob.fox.sleep", SA_NEW_fox_sleep3);
    repo.add("mob.fox.sleep", SA_NEW_fox_sleep4);
    repo.add("mob.fox.sleep", SA_NEW_fox_sleep5);
    repo.add("mob.fox.sniff", SA_NEW_fox_sniff1);
    repo.add("mob.fox.sniff", SA_NEW_fox_sniff2);
    repo.add("mob.fox.sniff", SA_NEW_fox_sniff3);
    repo.add("mob.fox.sniff", SA_NEW_fox_sniff4);
    repo.add("mob.fox.spit", SA_NEW_fox_spit1);
    repo.add("mob.fox.spit", SA_NEW_fox_spit2);
    repo.add("mob.fox.spit", SA_NEW_fox_spit3);
    repo.add("mob.silverfish.hit", SA_NEW_silverfish_hit1);
    repo.add("mob.silverfish.hit", SA_NEW_silverfish_hit2);
    repo.add("mob.silverfish.hit", SA_NEW_silverfish_hit3);
    repo.add("mob.silverfish.kill", SA_NEW_silverfish_kill);
    repo.add("mob.silverfish.say", SA_NEW_silverfish_say1);
    repo.add("mob.silverfish", SA_NEW_silverfish_say1);
    repo.add("mob.silverfish.say", SA_NEW_silverfish_say2);
    repo.add("mob.silverfish", SA_NEW_silverfish_say2);
    repo.add("mob.silverfish.say", SA_NEW_silverfish_say3);
    repo.add("mob.silverfish", SA_NEW_silverfish_say3);
    repo.add("mob.silverfish.say", SA_NEW_silverfish_say4);
    repo.add("mob.silverfish", SA_NEW_silverfish_say4);
    repo.add("mob.silverfish.step", SA_NEW_silverfish_step1);
    repo.add("mob.silverfish.step", SA_NEW_silverfish_step2);
    repo.add("mob.silverfish.step", SA_NEW_silverfish_step3);
    repo.add("mob.silverfish.step", SA_NEW_silverfish_step4);
    repo.add("mob.villager", SA_NEW_villager_idle1);
    repo.add("mob.villager", SA_NEW_villager_idle2);
    repo.add("mob.villager", SA_NEW_villager_idle3);
    repo.add("mob.villagerhurt", SA_NEW_villager_hit1);
    repo.add("mob.villagerhurt", SA_NEW_villager_hit2);
    repo.add("mob.villagerhurt", SA_NEW_villager_hit3);
    repo.add("mob.villagerhurt", SA_NEW_villager_hit4);
    repo.add("mob.villagerdie", SA_NEW_villager_death);
    repo.add("mob.villager.haggle", SA_NEW_villager_haggle1);
    repo.add("mob.villager.haggle", SA_NEW_villager_haggle2);
    repo.add("mob.villager.haggle", SA_NEW_villager_haggle3);
    repo.add("mob.villager.yes", SA_NEW_villager_yes1);
    repo.add("mob.villager.yes", SA_NEW_villager_yes2);
    repo.add("mob.villager.yes", SA_NEW_villager_yes3);
    repo.add("mob.villager.no", SA_NEW_villager_no1);
    repo.add("mob.villager.no", SA_NEW_villager_no2);
    repo.add("mob.villager.no", SA_NEW_villager_no3);
    repo.add("block.sweet_berry_bush.break", SA_NEW_sweet_berry_bush_break1);
    repo.add("block.sweet_berry_bush.break", SA_NEW_sweet_berry_bush_break2);
    repo.add("block.sweet_berry_bush.break", SA_NEW_sweet_berry_bush_break3);
    repo.add("block.sweet_berry_bush.break", SA_NEW_sweet_berry_bush_break4);
    repo.add("block.sweet_berry_bush.pick_berries", SA_NEW_sweet_berry_bush_pick1);
    repo.add("block.sweet_berry_bush.pick_berries", SA_NEW_sweet_berry_bush_pick2);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place1);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place2);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place3);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place4);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place5);
    repo.add("block.sweet_berry_bush.place", SA_NEW_sweet_berry_bush_place6);
}
